# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/api directory
sphinx:
  configuration: docs/api/conf.py
  fail_on_warning: false

# Python version and environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # Fetch tags for version detection
      - git fetch --unshallow || true
      - git fetch --tags || true

# Python dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: requirements.txt

# Output formats
formats:
  - pdf
  - epub
