//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SerialNumbers {
    
    private SerialNumbersSN[] snField;
    
    private string requestTypeField;
    
    private string serialNumberTypeField;
    
    private System.DateTime reservedUTCField;
    
    private string siteNameField;
    
    private string stationNameField;
    
    private int batchSizeField;
    
    private int fetchWhenLessThanField;
    
    private bool fetchWhenLessThanFieldSpecified;
    
    private string receiptField;
    
    private string tokenIdField;
    
    private string urlField;
    
    private bool onlyInSequenceField;
    
    private bool onlyInSequenceFieldSpecified;
    
    private string refSNField;
    
    private string refPNField;
    
    private string fromSerialNumberField;
    
    private bool reuseOnDuplicateRequestField;
    
    private bool reuseOnDuplicateRequestFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SN")]
    public SerialNumbersSN[] SN {
        get {
            return this.snField;
        }
        set {
            this.snField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string requestType {
        get {
            return this.requestTypeField;
        }
        set {
            this.requestTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string serialNumberType {
        get {
            return this.serialNumberTypeField;
        }
        set {
            this.serialNumberTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime reservedUTC {
        get {
            return this.reservedUTCField;
        }
        set {
            this.reservedUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string siteName {
        get {
            return this.siteNameField;
        }
        set {
            this.siteNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stationName {
        get {
            return this.stationNameField;
        }
        set {
            this.stationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int batchSize {
        get {
            return this.batchSizeField;
        }
        set {
            this.batchSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int fetchWhenLessThan {
        get {
            return this.fetchWhenLessThanField;
        }
        set {
            this.fetchWhenLessThanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fetchWhenLessThanSpecified {
        get {
            return this.fetchWhenLessThanFieldSpecified;
        }
        set {
            this.fetchWhenLessThanFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string receipt {
        get {
            return this.receiptField;
        }
        set {
            this.receiptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tokenId {
        get {
            return this.tokenIdField;
        }
        set {
            this.tokenIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool onlyInSequence {
        get {
            return this.onlyInSequenceField;
        }
        set {
            this.onlyInSequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool onlyInSequenceSpecified {
        get {
            return this.onlyInSequenceFieldSpecified;
        }
        set {
            this.onlyInSequenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refSN {
        get {
            return this.refSNField;
        }
        set {
            this.refSNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refPN {
        get {
            return this.refPNField;
        }
        set {
            this.refPNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fromSerialNumber {
        get {
            return this.fromSerialNumberField;
        }
        set {
            this.fromSerialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool reuseOnDuplicateRequest {
        get {
            return this.reuseOnDuplicateRequestField;
        }
        set {
            this.reuseOnDuplicateRequestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool reuseOnDuplicateRequestSpecified {
        get {
            return this.reuseOnDuplicateRequestFieldSpecified;
        }
        set {
            this.reuseOnDuplicateRequestFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SerialNumbersSN {
    
    private string idField;
    
    private System.DateTime takenField;
    
    private bool takenFieldSpecified;
    
    private int seqField;
    
    private bool seqFieldSpecified;
    
    private string refSNField;
    
    private string refPNField;
    
    private string refStnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime taken {
        get {
            return this.takenField;
        }
        set {
            this.takenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool takenSpecified {
        get {
            return this.takenFieldSpecified;
        }
        set {
            this.takenFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seqSpecified {
        get {
            return this.seqFieldSpecified;
        }
        set {
            this.seqFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refSN {
        get {
            return this.refSNField;
        }
        set {
            this.refSNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refPN {
        get {
            return this.refPNField;
        }
        set {
            this.refPNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refStn {
        get {
            return this.refStnField;
        }
        set {
            this.refStnField = value;
        }
    }
}
