//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PackageFolder))]
    [KnownType(typeof(Status))]
    [KnownType(typeof(VirtualFolder))]
    [KnownType(typeof(PackageSiteRelation))]
    public partial class Package: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid PackageId
        {
            get { return _packageId; }
            set
            {
                if (_packageId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PackageId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _packageId = value;
                    OnPropertyChanged("PackageId");
                }
            }
        }
        private System.Guid _packageId;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public int Version
        {
            get { return _version; }
            set
            {
                if (_version != value)
                {
                    _version = value;
                    OnPropertyChanged("Version");
                }
            }
        }
        private int _version;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;
    
        [DataMember]
        public string RootDirectory
        {
            get { return _rootDirectory; }
            set
            {
                if (_rootDirectory != value)
                {
                    _rootDirectory = value;
                    OnPropertyChanged("RootDirectory");
                }
            }
        }
        private string _rootDirectory;
    
        [DataMember]
        public string Tags
        {
            get { return _tags; }
            set
            {
                if (_tags != value)
                {
                    _tags = value;
                    OnPropertyChanged("Tags");
                }
            }
        }
        private string _tags;
    
        [DataMember]
        public System.DateTime Modified
        {
            get { return _modified; }
            set
            {
                if (_modified != value)
                {
                    _modified = value;
                    OnPropertyChanged("Modified");
                }
            }
        }
        private System.DateTime _modified;
    
        [DataMember]
        public string Responsible
        {
            get { return _responsible; }
            set
            {
                if (_responsible != value)
                {
                    _responsible = value;
                    OnPropertyChanged("Responsible");
                }
            }
        }
        private string _responsible;
    
        [DataMember]
        public int Status
        {
            get { return _status; }
            set
            {
                if (_status != value)
                {
                    ChangeTracker.RecordOriginalValue("Status", _status);
                    if (!IsDeserializing)
                    {
                        if (PackageStatus != null && PackageStatus.StatusId != value)
                        {
                            PackageStatus = null;
                        }
                    }
                    _status = value;
                    OnPropertyChanged("Status");
                }
            }
        }
        private int _status;
    
        [DataMember]
        public bool PackageFolder
        {
            get { return _packageFolder; }
            set
            {
                if (_packageFolder != value)
                {
                    _packageFolder = value;
                    OnPropertyChanged("PackageFolder");
                }
            }
        }
        private bool _packageFolder = true;
    
        [DataMember]
        public Nullable<System.Guid> VirtualFolderId
        {
            get { return _virtualFolderId; }
            set
            {
                if (_virtualFolderId != value)
                {
                    ChangeTracker.RecordOriginalValue("VirtualFolderId", _virtualFolderId);
                    if (!IsDeserializing)
                    {
                        if (VirtualFolder != null && VirtualFolder.VirtualFolderId != value)
                        {
                            VirtualFolder = null;
                        }
                    }
                    _virtualFolderId = value;
                    OnPropertyChanged("VirtualFolderId");
                }
            }
        }
        private Nullable<System.Guid> _virtualFolderId;
    
        [DataMember]
        public int Priority
        {
            get { return _priority; }
            set
            {
                if (_priority != value)
                {
                    _priority = value;
                    OnPropertyChanged("Priority");
                }
            }
        }
        private int _priority;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<PackageFolder> PackageFolders
        {
            get
            {
                if (_packageFolders == null)
                {
                    _packageFolders = new TrackableCollection<PackageFolder>();
                    _packageFolders.CollectionChanged += FixupPackageFolders;
                }
                return _packageFolders;
            }
            set
            {
                if (!ReferenceEquals(_packageFolders, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_packageFolders != null)
                    {
                        _packageFolders.CollectionChanged -= FixupPackageFolders;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (PackageFolder item in _packageFolders)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _packageFolders = value;
                    if (_packageFolders != null)
                    {
                        _packageFolders.CollectionChanged += FixupPackageFolders;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (PackageFolder item in _packageFolders)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("PackageFolders");
                }
            }
        }
        private TrackableCollection<PackageFolder> _packageFolders;
    
        [DataMember]
        public Status PackageStatus
        {
            get { return _packageStatus; }
            set
            {
                if (!ReferenceEquals(_packageStatus, value))
                {
                    var previousValue = _packageStatus;
                    _packageStatus = value;
                    FixupPackageStatus(previousValue);
                    OnNavigationPropertyChanged("PackageStatus");
                }
            }
        }
        private Status _packageStatus;
    
        [DataMember]
        public VirtualFolder VirtualFolder
        {
            get { return _virtualFolder; }
            set
            {
                if (!ReferenceEquals(_virtualFolder, value))
                {
                    var previousValue = _virtualFolder;
                    _virtualFolder = value;
                    FixupVirtualFolder(previousValue);
                    OnNavigationPropertyChanged("VirtualFolder");
                }
            }
        }
        private VirtualFolder _virtualFolder;
    
        [DataMember]
        public TrackableCollection<PackageSiteRelation> PackageSiteRelations
        {
            get
            {
                if (_packageSiteRelations == null)
                {
                    _packageSiteRelations = new TrackableCollection<PackageSiteRelation>();
                    _packageSiteRelations.CollectionChanged += FixupPackageSiteRelations;
                }
                return _packageSiteRelations;
            }
            set
            {
                if (!ReferenceEquals(_packageSiteRelations, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_packageSiteRelations != null)
                    {
                        _packageSiteRelations.CollectionChanged -= FixupPackageSiteRelations;
                    }
                    _packageSiteRelations = value;
                    if (_packageSiteRelations != null)
                    {
                        _packageSiteRelations.CollectionChanged += FixupPackageSiteRelations;
                    }
                    OnNavigationPropertyChanged("PackageSiteRelations");
                }
            }
        }
        private TrackableCollection<PackageSiteRelation> _packageSiteRelations;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PackageFolders.Clear();
            PackageStatus = null;
            VirtualFolder = null;
            PackageSiteRelations.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupPackageStatus(Status previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Packages.Contains(this))
            {
                previousValue.Packages.Remove(this);
            }
    
            if (PackageStatus != null)
            {
                if (!PackageStatus.Packages.Contains(this))
                {
                    PackageStatus.Packages.Add(this);
                }
    
                Status = PackageStatus.StatusId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PackageStatus")
                    && (ChangeTracker.OriginalValues["PackageStatus"] == PackageStatus))
                {
                    ChangeTracker.OriginalValues.Remove("PackageStatus");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PackageStatus", previousValue);
                }
                if (PackageStatus != null && !PackageStatus.ChangeTracker.ChangeTrackingEnabled)
                {
                    PackageStatus.StartTracking();
                }
            }
        }
    
        private void FixupVirtualFolder(VirtualFolder previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Packages.Contains(this))
            {
                previousValue.Packages.Remove(this);
            }
    
            if (VirtualFolder != null)
            {
                if (!VirtualFolder.Packages.Contains(this))
                {
                    VirtualFolder.Packages.Add(this);
                }
    
                VirtualFolderId = VirtualFolder.VirtualFolderId;
            }
            else if (!skipKeys)
            {
                VirtualFolderId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("VirtualFolder")
                    && (ChangeTracker.OriginalValues["VirtualFolder"] == VirtualFolder))
                {
                    ChangeTracker.OriginalValues.Remove("VirtualFolder");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("VirtualFolder", previousValue);
                }
                if (VirtualFolder != null && !VirtualFolder.ChangeTracker.ChangeTrackingEnabled)
                {
                    VirtualFolder.StartTracking();
                }
            }
        }
    
        private void FixupPackageFolders(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PackageFolder item in e.NewItems)
                {
                    item.Package = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PackageFolders", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PackageFolder item in e.OldItems)
                {
                    if (ReferenceEquals(item.Package, this))
                    {
                        item.Package = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PackageFolders", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }
    
        private void FixupPackageSiteRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PackageSiteRelation item in e.NewItems)
                {
                    item.Package = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PackageSiteRelations", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PackageSiteRelation item in e.OldItems)
                {
                    if (ReferenceEquals(item.Package, this))
                    {
                        item.Package = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PackageSiteRelations", item);
                    }
                }
            }
        }

        #endregion
    }
}
