//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Site))]
    [KnownType(typeof(TestSequenceRelation))]
    public partial class TestSequenceSiteRelation: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid TestSequenceSiteRelationId
        {
            get { return _testSequenceSiteRelationId; }
            set
            {
                if (_testSequenceSiteRelationId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'TestSequenceSiteRelationId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _testSequenceSiteRelationId = value;
                    OnPropertyChanged("TestSequenceSiteRelationId");
                }
            }
        }
        private System.Guid _testSequenceSiteRelationId;
    
        [DataMember]
        public System.Guid TestSequenceRelationId
        {
            get { return _testSequenceRelationId; }
            set
            {
                if (_testSequenceRelationId != value)
                {
                    ChangeTracker.RecordOriginalValue("TestSequenceRelationId", _testSequenceRelationId);
                    if (!IsDeserializing)
                    {
                        if (TestSequenceRelation != null && TestSequenceRelation.TestSequenceRelationId != value)
                        {
                            TestSequenceRelation = null;
                        }
                    }
                    _testSequenceRelationId = value;
                    OnPropertyChanged("TestSequenceRelationId");
                }
            }
        }
        private System.Guid _testSequenceRelationId;
    
        [DataMember]
        public System.Guid SiteId
        {
            get { return _siteId; }
            set
            {
                if (_siteId != value)
                {
                    ChangeTracker.RecordOriginalValue("SiteId", _siteId);
                    if (!IsDeserializing)
                    {
                        if (Site != null && Site.SiteId != value)
                        {
                            Site = null;
                        }
                    }
                    _siteId = value;
                    OnPropertyChanged("SiteId");
                }
            }
        }
        private System.Guid _siteId;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Site Site
        {
            get { return _site; }
            set
            {
                if (!ReferenceEquals(_site, value))
                {
                    var previousValue = _site;
                    _site = value;
                    FixupSite(previousValue);
                    OnNavigationPropertyChanged("Site");
                }
            }
        }
        private Site _site;
    
        [DataMember]
        public TestSequenceRelation TestSequenceRelation
        {
            get { return _testSequenceRelation; }
            set
            {
                if (!ReferenceEquals(_testSequenceRelation, value))
                {
                    var previousValue = _testSequenceRelation;
                    _testSequenceRelation = value;
                    FixupTestSequenceRelation(previousValue);
                    OnNavigationPropertyChanged("TestSequenceRelation");
                }
            }
        }
        private TestSequenceRelation _testSequenceRelation;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Site = null;
            TestSequenceRelation = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupSite(Site previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TestSequenceSiteRelations.Contains(this))
            {
                previousValue.TestSequenceSiteRelations.Remove(this);
            }
    
            if (Site != null)
            {
                if (!Site.TestSequenceSiteRelations.Contains(this))
                {
                    Site.TestSequenceSiteRelations.Add(this);
                }
    
                SiteId = Site.SiteId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Site")
                    && (ChangeTracker.OriginalValues["Site"] == Site))
                {
                    ChangeTracker.OriginalValues.Remove("Site");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Site", previousValue);
                }
                if (Site != null && !Site.ChangeTracker.ChangeTrackingEnabled)
                {
                    Site.StartTracking();
                }
            }
        }
    
        private void FixupTestSequenceRelation(TestSequenceRelation previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TestSequenceSiteRelations.Contains(this))
            {
                previousValue.TestSequenceSiteRelations.Remove(this);
            }
    
            if (TestSequenceRelation != null)
            {
                if (!TestSequenceRelation.TestSequenceSiteRelations.Contains(this))
                {
                    TestSequenceRelation.TestSequenceSiteRelations.Add(this);
                }
    
                TestSequenceRelationId = TestSequenceRelation.TestSequenceRelationId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TestSequenceRelation")
                    && (ChangeTracker.OriginalValues["TestSequenceRelation"] == TestSequenceRelation))
                {
                    ChangeTracker.OriginalValues.Remove("TestSequenceRelation");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TestSequenceRelation", previousValue);
                }
                if (TestSequenceRelation != null && !TestSequenceRelation.ChangeTracker.ChangeTrackingEnabled)
                {
                    TestSequenceRelation.StartTracking();
                }
            }
        }

        #endregion

    }
}
