//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Site))]
    [KnownType(typeof(WorkflowRelation))]
    public partial class WorkflowRelationSiteRelation: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid WorkflowRelationSiteRelationId
        {
            get { return _workflowRelationSiteRelationId; }
            set
            {
                if (_workflowRelationSiteRelationId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'WorkflowRelationSiteRelationId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _workflowRelationSiteRelationId = value;
                    OnPropertyChanged("WorkflowRelationSiteRelationId");
                }
            }
        }
        private System.Guid _workflowRelationSiteRelationId;
    
        [DataMember]
        public System.Guid SiteId
        {
            get { return _siteId; }
            set
            {
                if (_siteId != value)
                {
                    ChangeTracker.RecordOriginalValue("SiteId", _siteId);
                    if (!IsDeserializing)
                    {
                        if (Site != null && Site.SiteId != value)
                        {
                            Site = null;
                        }
                    }
                    _siteId = value;
                    OnPropertyChanged("SiteId");
                }
            }
        }
        private System.Guid _siteId;
    
        [DataMember]
        public System.Guid WorkflowRelationId
        {
            get { return _workflowRelationId; }
            set
            {
                if (_workflowRelationId != value)
                {
                    ChangeTracker.RecordOriginalValue("WorkflowRelationId", _workflowRelationId);
                    if (!IsDeserializing)
                    {
                        if (WorkflowRelation != null && WorkflowRelation.WorkflowRelationId != value)
                        {
                            WorkflowRelation = null;
                        }
                    }
                    _workflowRelationId = value;
                    OnPropertyChanged("WorkflowRelationId");
                }
            }
        }
        private System.Guid _workflowRelationId;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Site Site
        {
            get { return _site; }
            set
            {
                if (!ReferenceEquals(_site, value))
                {
                    var previousValue = _site;
                    _site = value;
                    FixupSite(previousValue);
                    OnNavigationPropertyChanged("Site");
                }
            }
        }
        private Site _site;
    
        [DataMember]
        public WorkflowRelation WorkflowRelation
        {
            get { return _workflowRelation; }
            set
            {
                if (!ReferenceEquals(_workflowRelation, value))
                {
                    var previousValue = _workflowRelation;
                    _workflowRelation = value;
                    FixupWorkflowRelation(previousValue);
                    OnNavigationPropertyChanged("WorkflowRelation");
                }
            }
        }
        private WorkflowRelation _workflowRelation;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Site = null;
            WorkflowRelation = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupSite(Site previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowRelationSiteRelations.Contains(this))
            {
                previousValue.WorkflowRelationSiteRelations.Remove(this);
            }
    
            if (Site != null)
            {
                if (!Site.WorkflowRelationSiteRelations.Contains(this))
                {
                    Site.WorkflowRelationSiteRelations.Add(this);
                }
    
                SiteId = Site.SiteId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Site")
                    && (ChangeTracker.OriginalValues["Site"] == Site))
                {
                    ChangeTracker.OriginalValues.Remove("Site");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Site", previousValue);
                }
                if (Site != null && !Site.ChangeTracker.ChangeTrackingEnabled)
                {
                    Site.StartTracking();
                }
            }
        }
    
        private void FixupWorkflowRelation(WorkflowRelation previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowRelationSiteRelations.Contains(this))
            {
                previousValue.WorkflowRelationSiteRelations.Remove(this);
            }
    
            if (WorkflowRelation != null)
            {
                if (!WorkflowRelation.WorkflowRelationSiteRelations.Contains(this))
                {
                    WorkflowRelation.WorkflowRelationSiteRelations.Add(this);
                }
    
                WorkflowRelationId = WorkflowRelation.WorkflowRelationId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("WorkflowRelation")
                    && (ChangeTracker.OriginalValues["WorkflowRelation"] == WorkflowRelation))
                {
                    ChangeTracker.OriginalValues.Remove("WorkflowRelation");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("WorkflowRelation", previousValue);
                }
                if (WorkflowRelation != null && !WorkflowRelation.ChangeTracker.ChangeTrackingEnabled)
                {
                    WorkflowRelation.StartTracking();
                }
            }
        }

        #endregion

    }
}
