//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(WorkflowDefinition))]
    public partial class WorkflowDefinitionXaml: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid WorkflowDefinitionId
        {
            get { return _workflowDefinitionId; }
            set
            {
                if (_workflowDefinitionId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'WorkflowDefinitionId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (WorkflowDefinition != null && WorkflowDefinition.WorkflowDefinitionId != value)
                        {
                            WorkflowDefinition = null;
                        }
                    }
                    _workflowDefinitionId = value;
                    OnPropertyChanged("WorkflowDefinitionId");
                }
            }
        }
        private System.Guid _workflowDefinitionId;
    
        [DataMember]
        public string Definition
        {
            get { return _definition; }
            set
            {
                if (_definition != value)
                {
                    _definition = value;
                    OnPropertyChanged("Definition");
                }
            }
        }
        private string _definition;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public WorkflowDefinition WorkflowDefinition
        {
            get { return _workflowDefinition; }
            set
            {
                if (!ReferenceEquals(_workflowDefinition, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (WorkflowDefinitionId != value.WorkflowDefinitionId)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _workflowDefinition;
                    _workflowDefinition = value;
                    FixupWorkflowDefinition(previousValue);
                    OnNavigationPropertyChanged("WorkflowDefinition");
                }
            }
        }
        private WorkflowDefinition _workflowDefinition;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            WorkflowDefinition = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupWorkflowDefinition(WorkflowDefinition previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.WorkflowDefinitionXaml, this))
            {
                previousValue.WorkflowDefinitionXaml = null;
            }
    
            if (WorkflowDefinition != null)
            {
                WorkflowDefinition.WorkflowDefinitionXaml = this;
                WorkflowDefinitionId = WorkflowDefinition.WorkflowDefinitionId;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("WorkflowDefinition")
                    && (ChangeTracker.OriginalValues["WorkflowDefinition"] == WorkflowDefinition))
                {
                    ChangeTracker.OriginalValues.Remove("WorkflowDefinition");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("WorkflowDefinition", previousValue);
                }
                if (WorkflowDefinition != null && !WorkflowDefinition.ChangeTracker.ChangeTrackingEnabled)
                {
                    WorkflowDefinition.StartTracking();
                }
            }
        }

        #endregion

    }
}
