// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System.Collections.ObjectModel;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class Culture
    {
        internal napicontract.Culture _instance;

        internal Culture(napicontract.Culture instance)
        {
            _instance = instance;
        }

        public short CultureId
        {
            get => _instance.CultureId;
            set => _instance.CultureId = value;
        }

        public string CultureCode
        {
            get => _instance.CultureCode;
            set => _instance.CultureCode = value;
        }

        public string CultureName
        {
            get => _instance.CultureName;
            set => _instance.CultureName = value;
        }

        public Collection<Translation> Translations  // r/o: No back-support to TrackableCollection
        {
            get => new Collection<Translation>(_instance.Translations.Select(i => new Translation(i)).ToList());
            //set => _instance.Translations = value.Select(i => i._instance); //.ToTrackableCollection()
        }
    }
}
