// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;

namespace Virinco.WATS.Service.MES.Contract
{
    public partial class KeyValue
    {
        private napicontract.KeyValue _instance;

        internal KeyValue(napicontract.KeyValue instance)
        {
            _instance = instance;
        }

        public string Key
        {
            get => _instance.Key;
            set => _instance.Key = value;
        }

        public string Value
        {
            get => _instance.Value;
            set => _instance.Value = value;
        }

        public string Xml
        {
            get => _instance.Xml;
            set => _instance.Xml = value;
        }
    }
}
