// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class Message
    {
        internal napicontract.Message _instance;

        internal Message(napicontract.Message instance)
        {
            _instance = instance;
        }

        public System.Guid MessageId
        {
            get => _instance.MessageId;
            set => _instance.MessageId = value;
        }

        public string EnglishText
        {
            get => _instance.EnglishText;
            set => _instance.EnglishText = value;
        }

        public short Parameters
        {
            get => _instance.Parameters;
            set => _instance.Parameters = value;
        }

        public short Type
        {
            get => _instance.Type;
            set => _instance.Type = value;
        }

        public System.DateTime Created
        {
            get => _instance.Created;
            set => _instance.Created = value;
        }

        public Nullable<System.DateTime> RequestDate
        {
            get => _instance.RequestDate;
            set => _instance.RequestDate = value;
        }

        public Nullable<int> RequestCount
        {
            get => _instance.RequestCount;
            set => _instance.RequestCount = value;
        }

        public byte[] HashCode
        {
            get => _instance.HashCode;
            set => _instance.HashCode = value;
        }

        public IEnumerable<Translation> Translations // r/o : No back-support to TrackableCollection
        {
            get => _instance.Translations.Select(i => new Translation(i));
            //set => _instance.Translations = value.Select(i => i._instance).ToList(); // ToTrackableCollection??
        }
    }
}