// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public partial class Package
    {
        internal napicontract.Package _instance;

        internal Package(napicontract.Package instance)
        {
            _instance = instance;
        }
        public System.Guid PackageId
        {
            get => _instance.PackageId;
            set => _instance.PackageId = value;
        }

        public string Name
        {
            get => _instance.Name;
            set => _instance.Name = value;
        }

        public int Version
        {
            get => _instance.Version;
            set => _instance.Version = value;
        }

        public string Description
        {
            get => _instance.Description;
            set => _instance.Description = value;
        }

        public string RootDirectory
        {
            get => _instance.RootDirectory;
            set => _instance.RootDirectory = value;
        }

        public string Tags
        {
            get => _instance.Tags;
            set => _instance.Tags = value;
        }

        public System.DateTime Modified
        {
            get => _instance.Modified;
            set => _instance.Modified = value;
        }

        public string Responsible
        {
            get => _instance.Responsible;
            set => _instance.Responsible = value;
        }

        public int Status
        {
            get => _instance.Status;
            set => _instance.Status = value;
        }

        public bool PackageFolder
        {
            get => _instance.PackageFolder;
            set => _instance.PackageFolder = value;
        }

        public Nullable<System.Guid> VirtualFolderId
        {
            get => _instance.VirtualFolderId;
            set => _instance.VirtualFolderId = value;
        }

        public int Priority
        {
            get => _instance.Priority;
            set => _instance.Priority = value;
        }

        // From Part
        public string Validation
        {
            get => _instance.Validation;
            set => _instance.Validation = value;
        }

        public string ValidationDescription
        {
            get => _instance.ValidationDescription;
            set => _instance.ValidationDescription = value;
        }

        public bool IsExpanded
        {
            get => _instance.IsExpanded;
            set => _instance.IsExpanded = value;
        }

        public bool IsModified
        {
            get => _instance.IsModified;
            set => _instance.IsModified = value;
        }

        public bool ReadOnly // r/o
        {
            get => _instance.ReadOnly;
            //set => _instance.ReadOnly = value;
        }

        public bool IsRestricted
        {
            get => _instance.IsRestricted;
            set => _instance.IsRestricted = value;
        }

        public bool HasAccess(bool HasRestrictedAccess)
            => _instance.HasAccess(HasRestrictedAccess);

        /// <summary>
        /// Number of bytes needed to download the package. 
        /// A file will not be downloaded if an unmodified file already exists on the file system. 
        /// </summary>
        public long? DownloadSize
        {
            get => _instance.DownloadSize;
            set => _instance.DownloadSize = value;
        }

        /// <summary>
        /// New available version of the package. 
        ///  
        /// </summary>
        public int? AvailableVersion
        {
            get => _instance.AvailableVersion;
            set => _instance.AvailableVersion = value;
        }

        public IEnumerable<Tag> PackageTags // r/o: No back-support to ObservableCollection
        {
            get => _instance.PackageTags.Select(i => new Tag(i));
            //set => _instance.PackageTags.Select(i => new Tag(i)) = value; // ToObservableCollection()
        }

        /// <summary>
        /// Update Tags xml with values from the PackageTags collection
        /// </summary>
        public void UpdateTagXml()
            => _instance.UpdateTagXml();

        public IEnumerable<PackageFolder> PackageFolders // r/o: No back-support to TrackableCollection
        {
            get => _instance.PackageFolders.Select(i => new PackageFolder(i));
            //set => _instance.PackageFolders=value.Select(i => i._instance); // ToTrackableCollection()
        }

        public Status PackageStatus
        {
            get => new Status(_instance.PackageStatus);
            set => _instance.PackageStatus = value._instance;
        }

        public VirtualFolder VirtualFolder
        {
            get => new VirtualFolder(_instance.VirtualFolder);
            set => _instance.VirtualFolder = value._instance;
        }

        public IEnumerable<PackageSiteRelation> PackageSiteRelations // r/o: No back-support to TrackableCollection
        {
            get => _instance.PackageSiteRelations.Select(i => new PackageSiteRelation(i));
            //set => _instance.PackageSiteRelations = value.Select(i => i._instance); // ToTrackableCollection()
        }

    }
}
