// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class Process //: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        internal napicontract.Process _instance;

        internal napicontract.Process NewApiInstance
        {
            get => _instance;
            set => _instance = value;
        }
        internal Process(napicontract.Process instance)
        {
            _instance = instance;
        }

        public bool IsModified
        {
            get => _instance.IsModified;
            set => _instance.IsModified = value;
        }

        public System.Guid ProcessId
        {
            get => _instance.ProcessId;
            set => _instance.ProcessId = value;
        }

        public string Code
        {
            get => _instance.Code;
            set => _instance.Code = value;
        }

        public string Name
        {
            get => _instance.Name;
            set => _instance.Name = value;
        }

        public string Description
        {
            get => _instance.Description;
            set => _instance.Description = value;
        }

        public int ProcessIndex
        {
            get => _instance.ProcessIndex;
            set => _instance.ProcessIndex = value;
        }

        public int State
        {
            get => _instance.State;
            set => _instance.State = value;
        }

        public string Properties
        {
            get => _instance.Properties;
            set => _instance.Properties = value;
        }

        public bool IsTestOperation
        {
            get => _instance.IsTestOperation;
            set => _instance.IsTestOperation = value;
        }

        public bool IsWIPOperation
        {
            get => _instance.IsWIPOperation;
            set => _instance.IsWIPOperation = value;
        }

        public bool IsRepairOperation
        {
            get => _instance.IsRepairOperation;
            set => _instance.IsRepairOperation = value;
        }

        public IEnumerable<Unit> Units // r/o: No back-support to TrackableCollection
        {
            get => _instance.Units.Select(i => new Unit(i));
            //set => _instance.Units = value.Select(i => i._instance); // ToTrackableCollection()
        }

        // Used in IdentifyUUT Form (ref-parameter)
        //internal napicontract.Process AsNewApiProcess()
        //{
        //    return new napicontract.Process()
        //    {
        //        Code = this.Code,
        //        Name = this.Name,
        //        Description = this.Description,
        //        IsModified = this.IsModified,
        //        IsRepairOperation = this.IsRepairOperation,
        //        IsTestOperation = this.IsTestOperation,
        //        IsWIPOperation = this.IsWIPOperation,
        //        ProcessId = this.ProcessId,
        //        State = this.State,
        //        Properties = this.Properties,
        //        ProcessIndex = this.ProcessIndex
        //    };
        //}

        //internal void Update(Process p)
        //{
        //    _instance = p;
        //    Code = p.Code;
        //    Name = p.Name;
        //    Description = p.Description;
        //    IsModified = p.IsModified;
        //    IsRepairOperation = p.IsRepairOperation;
        //    IsTestOperation = p.IsTestOperation;
        //    IsWIPOperation = p.IsWIPOperation;
        //    ProcessId = p.ProcessId;
        //    State = p.State;
        //    Properties = p.Properties;
        //    ProcessIndex = p.ProcessIndex;
        //}
    }
}
