// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class Product
    {
        internal napicontract.Product _instance;

        internal Product(napicontract.Product instance)
        {
            _instance = instance;
        }

        public System.Guid ProductId
        {
            get => _instance.ProductId;
            set => _instance.ProductId = value;
        }

        public bool NonSerial
        {
            get => _instance.NonSerial;
            set => _instance.NonSerial = value;
        }

        public string PartNumber
        {
            get => _instance.PartNumber;
            set => _instance.PartNumber = value;
        }

        public string Name
        {
            get => _instance.Name;
            set => _instance.Name = value;
        }

        public string Description
        {
            get => _instance.Description;
            set => _instance.Description = value;
        }

        public string XMLData
        {
            get => _instance.XMLData;
            set => _instance.XMLData = value;
        }

        public int State
        {
            get => _instance.State;
            set => _instance.State = value;
        }

        public Nullable<System.Guid> ProductCategoryId
        {
            get => _instance.ProductCategoryId;
            set => _instance.ProductCategoryId = value;
        }

        public IEnumerable<ProductRelation> ChildProductRelations // r/o: No back-support to TrackableCollection
        {
            get => _instance.ChildProductRelations.Select(i => new ProductRelation(i));
            //set => _instance.ChildProductRelations = value.Select(i => i._instance); //.ToTrackableCollection()
        }

        public IEnumerable<ProductRelation> ParentProductRelations // r/o: No back-support to TrackableCollection
        {
            get => _instance.ParentProductRelations.Select(i => new ProductRelation(i));
            //set => _instance.ParentProductRelations = value.Select(i => i._instance); //.ToTrackableCollection()
        }

        public IEnumerable<ProductRevision> ProductRevisions // r/o: No back-support to TrackableCollection
        {
            get => _instance.ProductRevisions.Select(i => new ProductRevision(i));
            //set => _instance.ProductRevisions = value.Select(i => i._instance); //.ToTrackableCollection()
        }

        public IEnumerable<Unit> Units // r/o: No back-support to TrackableCollection
        {
            get => _instance.Units.Select(i => new Unit(i));
            //set => _instance.Units = value.Select(i => i._instance); //.ToTrackableCollection()
        }

        public ProductCategory ProductCategory
        {
            get => new ProductCategory(_instance.ProductCategory);
            set => _instance.ProductCategory = value._instance;
        }

        public IEnumerable<Order> Orders // r/o: No back-support to TrackableCollection
        {
            get => _instance.Orders.Select(i => new Order(i));
            //set => _instance.Orders = value.Select(i => i._instance); //.ToTrackableCollection()
        }
    }
}
