// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class ProductionBatch
    {
        internal napicontract.ProductionBatch _instance;

        internal ProductionBatch(napicontract.ProductionBatch instance)
        {
            _instance = instance;
        }

        public System.Guid ProductionBatchId
        {
            get => _instance.ProductionBatchId;
            set => _instance.ProductionBatchId = value;
        }

        public string BatchNumber
        {
            get => _instance.BatchNumber;
            set => _instance.BatchNumber = value;
        }

        public Nullable<int> BatchSize
        {
            get => _instance.BatchSize;
            set => _instance.BatchSize = value;
        }

        public string XMLData
        {
            get => _instance.XMLData;
            set => _instance.XMLData = value;
        }

        public Nullable<int> Produced
        {
            get => _instance.Produced;
            set => _instance.Produced = value;
        }

        public IEnumerable<Unit> Units // r/o: No back-support to TrackableCollection
        {
            get => _instance.Units.Select(i => new Unit(i));
            //set => _instance.Units = value.Select(i => i._instance); // ToTrackableCollection()
        }
    }
}
