// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class ProductCategory
    {
        internal napicontract.ProductCategory _instance;

        internal ProductCategory(napicontract.ProductCategory instance)
        {
            _instance = instance;
        }

        public System.Guid ProductCategoryId
        {
            get => _instance.ProductCategoryId;
            set => _instance.ProductCategoryId = value;
        }

        public Nullable<System.Guid> ParentProductCategoryId
        {
            get => _instance.ParentProductCategoryId;
            set => _instance.ParentProductCategoryId = value;
        }

        public string Name
        {
            get => _instance.Name;
            set => _instance.Name = value;
        }

        public string Description
        {
            get => _instance.Description;
            set => _instance.Description = value;
        }

        public string XMLData
        {
            get => _instance.XMLData;
            set => _instance.XMLData = value;
        }

        public byte[] Icon
        {
            get => _instance.Icon;
            set => _instance.Icon = value;
        }

        public Nullable<System.Guid> SiteId
        {
            get => _instance.SiteId;
            set => _instance.SiteId = value;
        }

        public IEnumerable<Product> Products // r/o: No back-support to TrackableCollection
        {
            get => _instance.Products.Select(i => new Product(i));
            //set => _instance.Products=value.Select(i => i._instance); // ToTrackableCollection()
        }

        public IEnumerable<ProductCategory> Children // r/o: No back-support to TrackableCollection
        {
            get => _instance.Children.Select(i => new ProductCategory(i));
            //set => _instance.Children=value.Select(i => i._instance); // ToTrackableCollection()
        }

        public ProductCategory Parent
        {
            get => new ProductCategory(_instance.Parent);
            set => _instance.Parent = value._instance;
        }

        public Site Site
        {
            get => new Site(_instance.Site);
            set => _instance.Site = value._instance;
        }
    }
}
