// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class Repository
    {
        internal napicontract.Repository _instance;

        internal Repository(napicontract.Repository instance)
        {
            _instance = instance;
        }

        public System.Guid RepositoryId
        {
            get => _instance.RepositoryId;
            set => _instance.RepositoryId = value;
        }

        public string Name
        {
            get => _instance.Name;
            set => _instance.Name = value;
        }

        public string Description
        {
            get => _instance.Description;
            set => _instance.Description = value;
        }

        public int Type
        {
            get => _instance.Type;
            set => _instance.Type = value;
        }

        public IEnumerable<RepositoryFolder> RepositoryFolders // r/o: No back-support to TrackableCollection
        {
            get => _instance.RepositoryFolders.Select(i => new RepositoryFolder(i));
            //set => _instance.RepositoryFolders = value.Select(i => i._instance); // ToTrackableCollection()
        }
    }
}
