// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class RepositoryFolderFile
    {
        internal napicontract.RepositoryFolderFile _instance;

        internal RepositoryFolderFile(napicontract.RepositoryFolderFile instance)
        {
            _instance = instance;
        }

        public System.Guid RepositoryFolderFileId
        {
            get => _instance.RepositoryFolderFileId;
            set => _instance.RepositoryFolderFileId = value;
        }

        public System.Guid RepositoryFolderId
        {
            get => _instance.RepositoryFolderId;
            set => _instance.RepositoryFolderId = value;
        }

        public string Name
        {
            get => _instance.Name;
            set => _instance.Name = value;
        }

        public int Version
        {
            get => _instance.Version;
            set => _instance.Version = value;
        }

        public string Description
        {
            get => _instance.Description;
            set => _instance.Description = value;
        }

        public System.DateTime Uploaded
        {
            get => _instance.Uploaded;
            set => _instance.Uploaded = value;
        }

        public System.DateTime FileModifiedDate
        {
            get => _instance.FileModifiedDate;
            set => _instance.FileModifiedDate = value;
        }

        public byte[] Checksum
        {
            get => _instance.Checksum;
            set => _instance.Checksum = value;
        }

        public Nullable<bool> Valid
        {
            get => _instance.Valid;
            set => _instance.Valid = value;
        }

        public string FileVersion
        {
            get => _instance.FileVersion;
            set => _instance.FileVersion = value;
        }

        public Nullable<long> FileSize
        {
            get => _instance.FileSize;
            set => _instance.FileSize = value;
        }

        public IEnumerable<PackageFolderFile> PackageFolderFiles // r/o: No back-support to TrackableCollection
        {
            get => _instance.PackageFolderFiles.Select(i => new PackageFolderFile(i)).ToList();
            //set => _instance.PackageFolderFiles = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public RepositoryFolder RepositoryFolder
        {
            get => new RepositoryFolder(_instance.RepositoryFolder);
            set => _instance.RepositoryFolder = value._instance;
        }

        public RepositoryFolderFileContent RepositoryFolderFileContent
        {
            get => new RepositoryFolderFileContent(_instance.RepositoryFolderFileContent);
            set => _instance.RepositoryFolderFileContent = value._instance;
        }
    }
}
