// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;

namespace Virinco.WATS.Service.MES.Contract
{
    public class RepositoryFolderFileContent
    {
        internal napicontract.RepositoryFolderFileContent _instance;

        internal RepositoryFolderFileContent(napicontract.RepositoryFolderFileContent instance)
        {
            _instance = instance;
        }

        public System.Guid RepositoryFolderFileId
        {
            get => _instance.RepositoryFolderFileId;
            set => _instance.RepositoryFolderFileId = value;
        }

        public byte[] Content
        {
            get => _instance.Content;
            set => _instance.Content = value;
        }

        public RepositoryFolderFile RepositoryFolderFile
        {
            get => new RepositoryFolderFile(_instance.RepositoryFolderFile);
            set => _instance.RepositoryFolderFile = value._instance;
        }
    }
}
