// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class RepositoryFolder
    {
        internal napicontract.RepositoryFolder _instance;

        internal RepositoryFolder(napicontract.RepositoryFolder instance)
        {
            _instance = instance;
        }

        public System.Guid RepositoryFolderId
        {
            get => _instance.RepositoryFolderId;
            set => _instance.RepositoryFolderId = value;
        }

        public System.Guid RepositoryId
        {
            get => _instance.RepositoryId;
            set => _instance.RepositoryId = value;
        }

        public Nullable<System.Guid> ParentFolderId
        {
            get => _instance.ParentFolderId;
            set => _instance.ParentFolderId = value;
        }

        public string Name
        {
            get => _instance.Name;
            set => _instance.Name = value;
        }

        public System.DateTime Modified
        {
            get => _instance.Modified;
            set => _instance.Modified = value;
        }

        public Repository Repository
        {
            get => new Repository(_instance.Repository);
            set => _instance.Repository = value._instance;
        }
        public IEnumerable<RepositoryFolder> RepositoryFolders // r/o: No back-support to TrackableCollection
        {
            get => _instance.RepositoryFolders.Select(r => new RepositoryFolder(r));
            //set => _instance.RepositoryFolders = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public RepositoryFolder Parent
        {
            get => new RepositoryFolder(_instance.Parent);
            set => _instance.Parent = value._instance;
        }

        public IEnumerable<RepositoryFolderFile> RepositoryFolderFiles // r/o: No back-support to TrackableCollection
        {
            get => _instance.RepositoryFolderFiles.Select(r => new RepositoryFolderFile(r));
            //set => _instance.RepositoryFolderFiles = value.Select(i => i._instance); // ToTrackableCollection()
        }
    }
}
