// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class Site
    {
        internal napicontract.Site _instance;

        internal Site(napicontract.Site instance)
        {
            _instance = instance;
        }

        public System.Guid SiteId
        {
            get => _instance.SiteId;
            set => _instance.SiteId = value;
        }

        public string Name
        {
            get => _instance.Name;
            set => _instance.Name = value;
        }

        public string Code
        {
            get => _instance.Code;
            set => _instance.Code = value;
        }

        public string XMLData
        {
            get => _instance.XMLData;
            set => _instance.XMLData = value;
        }

        public IEnumerable<Unit> Units // r/o: No back-support to TrackableCollection
        {
            get => _instance.Units.Select(i => new Unit(i));
            //set => _instance.Units = value.Select(i => i._instance); // ToTrackableCollection()
        }
        public IEnumerable<ProductCategory> ProductCategories // r/o: No back-support to TrackableCollection
        {
            get => _instance.ProductCategories.Select(i => new ProductCategory(i));
            //set => _instance.ProductCategories = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public IEnumerable<PackageSiteRelation> PackageSiteRelations // r/o: No back-support to TrackableCollection
        {
            get => _instance.PackageSiteRelations.Select(i => new PackageSiteRelation(i));
            //set => _instance.PackageSiteRelations = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public IEnumerable<WorkflowRelationSiteRelation> WorkflowRelationSiteRelations // r/o: No back-support to TrackableCollection
        {
            get => _instance.WorkflowRelationSiteRelations.Select(i => new WorkflowRelationSiteRelation(i));
            //set => _instance.WorkflowRelationSiteRelations = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public IEnumerable<Order> Orders // r/o: No back-support to TrackableCollection
        {
            get => _instance.Orders.Select(i => new Order(i));
            //set => _instance.Orders = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public IEnumerable<TestSequenceDefinition> TestSequenceDefinitions // r/o: No back-support to TrackableCollection
        {
            get => _instance.TestSequenceDefinitions.Select(i => new TestSequenceDefinition(i));
            //set => _instance.TestSequenceDefinitions = value.Select(i => i._instance); // ToTrackableCollection()
        }
        public IEnumerable<TestSequenceSiteRelation> TestSequenceSiteRelations // r/o: No back-support to TrackableCollection
        {
            get => _instance.TestSequenceSiteRelations.Select(i => new TestSequenceSiteRelation(i));
            //set => _instance.TestSequenceSiteRelations = value.Select(i => i._instance); // ToTrackableCollection()
        }
    }
}
