// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;

namespace Virinco.WATS.Service.MES.Contract
{
    public class TestSequenceProcessRelation
    {
        private napicontract.TestSequenceProcessRelation _instance;

        internal TestSequenceProcessRelation(napicontract.TestSequenceProcessRelation instance)
        {
            _instance = instance;
        }

        public System.Guid TestSequenceProcessRelationId
        {
            get => _instance.TestSequenceProcessRelationId;
            set => _instance.TestSequenceProcessRelationId = value;
        }

        public System.Guid TestSequenceRelationId
        {
            get => _instance.TestSequenceRelationId;
            set => _instance.TestSequenceRelationId = value;
        }

        public System.Guid ProcessId
        {
            get => _instance.ProcessId;
            set => _instance.ProcessId = value;
        }

        public TestSequenceRelation TestSequenceRelation
        {
            get => new TestSequenceRelation(_instance.TestSequenceRelation);
            set => _instance.TestSequenceRelation = value._instance;
        }
    }
}
