// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class TestSequenceRelation
    {
        internal napicontract.TestSequenceRelation _instance;

        internal TestSequenceRelation(napicontract.TestSequenceRelation instance)
        {
            _instance = instance;
        }

        public System.Guid TestSequenceRelationId
        {
            get => _instance.TestSequenceRelationId;
            set => _instance.TestSequenceRelationId = value;
        }

        public System.Guid TestSequenceDefinitionId
        {
            get => _instance.TestSequenceDefinitionId;
            set => _instance.TestSequenceDefinitionId = value;
        }

        public string EntitySchema
        {
            get => _instance.EntitySchema;
            set => _instance.EntitySchema = value;
        }

        public string EntityName
        {
            get => _instance.EntityName;
            set => _instance.EntityName = value;
        }

        public string EntityKey
        {
            get => _instance.EntityKey;
            set => _instance.EntityKey = value;
        }

        public string EntityValue
        {
            get => _instance.EntityValue;
            set => _instance.EntityValue = value;
        }

        public int Status
        {
            get => _instance.Status;
            set => _instance.Status = value;
        }

        public TestSequenceDefinition TestSequenceDefinition
        {
            get => new TestSequenceDefinition(_instance.TestSequenceDefinition);
            set => _instance.TestSequenceDefinition = value._instance;
        }

        public IEnumerable<TestSequenceSiteRelation> TestSequenceSiteRelations // r/o: No back-support to TrackableCollection
        {
            get => _instance.TestSequenceSiteRelations.Select(i => new TestSequenceSiteRelation(i));
            //set => _instance.TestSequenceSiteRelations = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public IEnumerable<TestSequenceProcessRelation> TestSequenceProcessRelations // r/o: No back-support to TrackableCollection
        {
            get => _instance.TestSequenceProcessRelations.Select(i => new TestSequenceProcessRelation(i));
            //set => _instance.TestSequenceProcessRelations = value.Select(i => i._instance); // ToTrackableCollection()
        }
    }
}
