// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;

namespace Virinco.WATS.Service.MES.Contract
{
    public class TestSequenceInstance
    {
        private napicontract.TestSequenceInstance _instance;

        internal TestSequenceInstance(napicontract.TestSequenceInstance instance)
        {
            _instance = instance;
        }

        public System.Guid TestSequenceInstanceId
        {
            get => _instance.TestSequenceInstanceId;
            set => _instance.TestSequenceInstanceId = value;
        }

        public System.Guid TestSequenceDefinitionId
        {
            get => _instance.TestSequenceDefinitionId;
            set => _instance.TestSequenceDefinitionId = value;
        }

        public Nullable<System.Guid> UnitId
        {
            get => _instance.UnitId;
            set => _instance.UnitId = value;
        }

        public string SerialNumber
        {
            get => _instance.SerialNumber;
            set => _instance.SerialNumber = value;
        }

        public string PartNumber
        {
            get => _instance.PartNumber;
            set => _instance.PartNumber = value;
        }

        public string Revision
        {
            get => _instance.Revision;
            set => _instance.Revision = value;
        }

        public System.DateTime Created
        {
            get => _instance.Created;
            set => _instance.Created = value;
        }

        public System.DateTime LastEventTime
        {
            get => _instance.LastEventTime;
            set => _instance.LastEventTime = value;
        }

        public string Instance
        {
            get => _instance.Instance;
            set => _instance.Instance = value;
        }

        public Nullable<System.Guid> ProcessId
        {
            get => _instance.ProcessId;
            set => _instance.ProcessId = value;
        }

        public Nullable<System.Guid> RepairProcessId
        {
            get => _instance.RepairProcessId;
            set => _instance.RepairProcessId = value;
        }

        public TestSequenceDefinition TestSequenceDefinition
        {
            get => new TestSequenceDefinition(_instance.TestSequenceDefinition);
            set => _instance.TestSequenceDefinition = value._instance;
        }
    }
}
