// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;

namespace Virinco.WATS.Service.MES.Contract
{
    public class TestSequenceSiteRelation
    {
        private napicontract.TestSequenceSiteRelation _instance;

        internal TestSequenceSiteRelation(napicontract.TestSequenceSiteRelation instance)
        {
            _instance = instance;
        }

        public System.Guid TestSequenceSiteRelationId
        {
            get => _instance.TestSequenceSiteRelationId;
            set => _instance.TestSequenceSiteRelationId = value;
        }

        public System.Guid TestSequenceRelationId
        {
            get => _instance.TestSequenceRelationId;
            set => _instance.TestSequenceRelationId = value;
        }

        public System.Guid SiteId
        {
            get => _instance.SiteId;
            set => _instance.SiteId = value;
        }

        public Site Site
        {
            get => new Site(_instance.Site);
            set => _instance.Site = value._instance;
        }

        public TestSequenceRelation TestSequenceRelation
        {
            get => new TestSequenceRelation(_instance.TestSequenceRelation);
            set => _instance.TestSequenceRelation = value._instance;
        }
    }
}
