// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;

namespace Virinco.WATS.Service.MES.Contract
{
    public class TestSequenceDefinitionMedia
    {
        private napicontract.TestSequenceDefinitionMedia _instance;

        internal TestSequenceDefinitionMedia(napicontract.TestSequenceDefinitionMedia instance)
        {
            _instance = instance;
        }

        public System.Guid TestSequenceDefinitionMediaId
        {
            get => _instance.TestSequenceDefinitionMediaId;
            set => _instance.TestSequenceDefinitionMediaId = value;
        }

        public System.Guid TestSequenceDefinitionId
        {
            get => _instance.TestSequenceDefinitionId;
            set => _instance.TestSequenceDefinitionId = value;
        }

        public System.Guid RepositoryFolderFileId
        {
            get => _instance.RepositoryFolderFileId;
            set => _instance.RepositoryFolderFileId = value;
        }

        public TestSequenceDefinition TestSequenceDefinition
        {
            get => new TestSequenceDefinition(_instance.TestSequenceDefinition);
            set => _instance.TestSequenceDefinition = value._instance;
        }
    }
}
