// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class Unit
    {
        internal napicontract.Unit _instance;

        internal Unit(napicontract.Unit instance)
        {
            _instance = instance;
        }

        public System.Guid UnitId
        {
            get => _instance.UnitId;
            set => _instance.UnitId = value;
        }

        public Nullable<System.Guid> ParentUnitId
        {
            get => _instance.ParentUnitId;
            set => _instance.ParentUnitId = value;
        }

        public System.Guid ProductRevisionId
        {
            get => _instance.ProductRevisionId;
            set => _instance.ProductRevisionId = value;
        }

        public Nullable<System.Guid> SiteId
        {
            get => _instance.SiteId;
            set => _instance.SiteId = value;
        }

        public Nullable<System.Guid> ProductionBatchId
        {
            get => _instance.ProductionBatchId;
            set => _instance.ProductionBatchId = value;
        }

        public string SerialNumber
        {
            get => _instance.SerialNumber;
            set => _instance.SerialNumber = value;
        }

        public Nullable<System.DateTime> SerialDate
        {
            get => _instance.SerialDate;
            set => _instance.SerialDate = value;
        }

        public string XMLData
        {
            get => _instance.XMLData;
            set => _instance.XMLData = value;
        }

        public string CurrentLocation
        {
            get => _instance.CurrentLocation;
            set => _instance.CurrentLocation = value;
        }

        public byte[] TStamp
        {
            get => _instance.TStamp;
            set => _instance.TStamp = value;
        }

        public bool Changed
        {
            get => _instance.Changed;
            set => _instance.Changed = value;
        }

        public int UnitPhaseId
        {
            get => _instance.UnitPhaseId;
            set => _instance.UnitPhaseId = value;
        }

        public System.Guid ProductId
        {
            get => _instance.ProductId;
            set => _instance.ProductId = value;
        }

        public Nullable<System.Guid> ProcessId
        {
            get => _instance.ProcessId;
            set => _instance.ProcessId = value;
        }

        public Nullable<System.Guid> OrderId
        {
            get => _instance.OrderId;
            set => _instance.OrderId = value;
        }

        public Site Site
        {
            get => new Site(_instance.Site);
            set => _instance.Site = value._instance;
        }

        public ProductRevision ProductRevision
        {
            get => new ProductRevision(_instance.ProductRevision);
            set => _instance.ProductRevision = value._instance;
        }

        public ProductionBatch ProductionBatch
        {
            get => new ProductionBatch(_instance.ProductionBatch);
            set => _instance.ProductionBatch = value._instance;
        }

        public IEnumerable<Unit> Children // r/o: No back-support to TrackableCollection
        {
            get => _instance.Children.Select(i => new Unit(i));
            //set => _instance.Children = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public Unit Parent
        {
            get => new Unit(_instance.Parent);
            set => _instance.Parent = value._instance;
        }

        public IEnumerable<WorkflowInstance> WorkflowInstances // r/o: No back-support to TrackableCollection
        {
            get => _instance.WorkflowInstances.Select(i => new WorkflowInstance(i));
            //set => _instance.WorkflowInstances = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public UnitPhase UnitPhase
        {
            get => new UnitPhase(_instance.UnitPhase);
            set => _instance.UnitPhase = value._instance;
        }

        public Product Product
        {
            get => new Product(_instance.Product);
            set => _instance.Product = value._instance;
        }

        public Process Process
        {
            get => new Process(_instance.Process);
            set => _instance.Process = value._instance;
        }

        public Order Order
        {
            get => new Order(_instance.Order);
            set => _instance.Order = value._instance;
        }
    }
}
