// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class VirtualFolder
    {
        internal napicontract.VirtualFolder _instance;

        internal VirtualFolder(napicontract.VirtualFolder instance)
        {
            _instance = instance;
        }

        public System.Guid VirtualFolderId
        {
            get => _instance.VirtualFolderId;
            set => _instance.VirtualFolderId = value;
        }

        public Nullable<System.Guid> ParentVirtualFolderId
        {
            get => _instance.ParentVirtualFolderId;
            set => _instance.ParentVirtualFolderId = value;
        }

        public string Name
        {
            get => _instance.Name;
            set => _instance.Name = value;
        }

        public string Description
        {
            get => _instance.Description;
            set => _instance.Description = value;
        }

        public int Type
        {
            get => _instance.Type;
            set => _instance.Type = value;
        }

        public IEnumerable<VirtualFolder> Children // r/o: No back-support to TrackableCollection
        {
            get => _instance.Children.Select(child => new VirtualFolder(child));
            //set => _instance.Children = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public VirtualFolder Parent
        {
            get => new VirtualFolder(_instance.Parent);
            set => _instance.Parent = value._instance;
        }

        public IEnumerable<WorkflowDefinition> WorkflowDefinitions // r/o: No back-support to TrackableCollection
        {
            get => _instance.WorkflowDefinitions.Select(i => new WorkflowDefinition(i));
            //set => _instance.WorkflowDefinitions = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public IEnumerable<Package> Packages // r/o: No back-support to TrackableCollection
        {
            get => _instance.Packages.Select(i => new Package(i));
            //set => _instance.Packages = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public IEnumerable<TestSequenceDefinition> TestSequenceDefinitions // r/o: No back-support to TrackableCollection
        {
            get => _instance.TestSequenceDefinitions.Select(i => new TestSequenceDefinition(i));
            //set => _instance.TestSequenceDefinitions = value.Select(i => i._instance); // ToTrackableCollection()
        }

    }
}
