// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class WorkflowRelation
    {
        internal napicontract.WorkflowRelation _instance;

        internal WorkflowRelation(napicontract.WorkflowRelation instance)
        {
            _instance = instance;
        }

        public System.Guid WorkflowRelationId
        {
            get => _instance.WorkflowRelationId;
            set => _instance.WorkflowRelationId = value;
        }

        public System.Guid WorkflowDefinitionId
        {
            get => _instance.WorkflowDefinitionId;
            set => _instance.WorkflowDefinitionId = value;
        }

        public string EntitySchema
        {
            get => _instance.EntitySchema;
            set => _instance.EntitySchema = value;
        }

        public string EntityName
        {
            get => _instance.EntityName;
            set => _instance.EntityName = value;
        }

        public string EntityKeyName
        {
            get => _instance.EntityKeyName;
            set => _instance.EntityKeyName = value;
        }

        public int Status
        {
            get => _instance.Status;
            set => _instance.Status = value;
        }

        public string EntityValue
        {
            get => _instance.EntityValue;
            set => _instance.EntityValue = value;
        }

        public string Parameters
        {
            get => _instance.Parameters;
            set => _instance.Parameters = value;
        }
        public IEnumerable<WorkflowInstance> WorkflowInstances // r/o: No back-support to TrackableCollection
        {
            get => _instance.WorkflowInstances.Select(i => new WorkflowInstance(i));
            //set => _instance.WorkflowInstances = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public WorkflowDefinition WorkflowDefinition
        {
            get => new WorkflowDefinition(_instance.WorkflowDefinition);
            set => _instance.WorkflowDefinition = value._instance;
        }

        public IEnumerable<WorkflowRelationSiteRelation> WorkflowRelationSiteRelations // r/o: No back-support to TrackableCollection
        {
            get => _instance.WorkflowRelationSiteRelations.Select(i => new WorkflowRelationSiteRelation(i));
            //set => _instance.WorkflowRelationSiteRelations = value.Select(i => i._instance); // ToTrackableCollection()
        }
    }
}
