// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class WorkflowInstance
    {
        private napicontract.WorkflowInstance _instance;

        internal WorkflowInstance(napicontract.WorkflowInstance instance)
        {
            _instance = instance;
        }

        public System.Guid WorkflowId
        {
            get => _instance.WorkflowId;
            set => _instance.WorkflowId = value;
        }

        public Nullable<System.Guid> ParentWorkflowId
        {
            get => _instance.ParentWorkflowId;
            set => _instance.ParentWorkflowId = value;
        }

        public System.Guid WorkflowDefinitionId
        {
            get => _instance.WorkflowDefinitionId;
            set => _instance.WorkflowDefinitionId = value;
        }

        public Nullable<System.Guid> WorkflowRelationId
        {
            get => _instance.WorkflowRelationId;
            set => _instance.WorkflowRelationId = value;
        }

        public System.Guid UnitId
        {
            get => _instance.UnitId;
            set => _instance.UnitId = value;
        }

        public int State
        {
            get => _instance.State;
            set => _instance.State = value;
        }

        public Nullable<System.Guid> NativeWorkflowInstanceId
        {
            get => _instance.NativeWorkflowInstanceId;
            set => _instance.NativeWorkflowInstanceId = value;
        }

        public Nullable<System.Guid> LastWorkflowActivityId
        {
            get => _instance.LastWorkflowActivityId;
            set => _instance.LastWorkflowActivityId = value;
        }

        public Nullable<int> LastActivityLogId
        {
            get => _instance.LastActivityLogId;
            set => _instance.LastActivityLogId = value;
        }

        public Nullable<System.DateTime> LastEventTime
        {
            get => _instance.LastEventTime;
            set => _instance.LastEventTime = value;
        }

        public Nullable<int> CurrentActivityLogId
        {
            get => _instance.CurrentActivityLogId;
            set => _instance.CurrentActivityLogId = value;
        }

        public Nullable<int> WorkflowServiceVersion
        {
            get => _instance.WorkflowServiceVersion;
            set => _instance.WorkflowServiceVersion = value;
        }

        public Nullable<System.Guid> SiteId
        {
            get => _instance.SiteId;
            set => _instance.SiteId = value;
        }

        public System.DateTime Created
        {
            get => _instance.Created;
            set => _instance.Created = value;
        }

        public Unit Unit
        {
            get => new Unit(_instance.Unit);
            set => _instance.Unit = value._instance;
        }

        public IEnumerable<WorkflowInstance> Children // r/o: No back-support to TrackableCollection
        {
            get => _instance.Children.Select(i => new WorkflowInstance(i));
            //set => _instance.Children = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public WorkflowInstance Parent
        {
            get => new WorkflowInstance(_instance.Parent);
            set => _instance.Parent = value._instance;
        }

        public WorkflowRelation WorkflowRelation
        {
            get => new WorkflowRelation(_instance.WorkflowRelation);
            set => _instance.WorkflowRelation = value._instance;
        }

        public WorkflowDefinition WorkflowDefinition
        {
            get => new WorkflowDefinition(_instance.WorkflowDefinition);
            set => _instance.WorkflowDefinition = value._instance;
        }

        public WorkflowActivity WorkflowActivity
        {
            get => new WorkflowActivity(_instance.WorkflowActivity);
            set => _instance.WorkflowActivity = value._instance;
        }
    }
}
