// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System;

namespace Virinco.WATS.Service.MES.Contract
{
    public class WorkflowActivityLog
    {
        private napicontract.WorkflowActivityLog _instance;

        internal WorkflowActivityLog(napicontract.WorkflowActivityLog instance)
        {
            _instance = instance;
        }

        public int WorkflowActivityLogId
        {
            get => _instance.WorkflowActivityLogId;
            set => _instance.WorkflowActivityLogId = value;
        }

        public System.Guid WorkflowId
        {
            get => _instance.WorkflowId;
            set => _instance.WorkflowId = value;
        }

        public Nullable<System.Guid> WorkflowActivityId
        {
            get => _instance.WorkflowActivityId;
            set => _instance.WorkflowActivityId = value;
        }

        public string ActivityType
        {
            get => _instance.ActivityType;
            set => _instance.ActivityType = value;
        }

        public string ProcessCode
        {
            get => _instance.ProcessCode;
            set => _instance.ProcessCode = value;
        }

        public System.DateTime Start
        {
            get => _instance.Start;
            set => _instance.Start = value;
        }

        public Nullable<System.DateTime> End
        {
            get => _instance.End;
            set => _instance.End = value;
        }

        public string Description
        {
            get => _instance.Description;
            set => _instance.Description = value;
        }

        public WorkflowActivity WorkflowActivity
        {
            get => new WorkflowActivity(_instance.WorkflowActivity);
            set => _instance.WorkflowActivity = value._instance;
        }
    }
}
