// Originally auto-generated by entity framework, reworked to act as a wrapper around the WATS Client Api in WATS Client 7.0
extern alias newclientapi;

using napicontract = newclientapi::Virinco.WATS.Service.MES.Contract;
using System.Collections.Generic;
using System.Linq;

namespace Virinco.WATS.Service.MES.Contract
{
    public class WorkflowActivity
    {
        internal napicontract.WorkflowActivity _instance;

        internal WorkflowActivity(napicontract.WorkflowActivity instance)
        {
            _instance = instance;
        }

        public System.Guid WorkflowActivityId
        {
            get => _instance.WorkflowActivityId;
            set => _instance.WorkflowActivityId = value;
        }

        public System.Guid WorkflowDefinitionId
        {
            get => _instance.WorkflowDefinitionId;
            set => _instance.WorkflowDefinitionId = value;
        }

        public string ActivityPath
        {
            get => _instance.ActivityPath;
            set => _instance.ActivityPath = value;
        }

        public string ActivityName
        {
            get => _instance.ActivityName;
            set => _instance.ActivityName = value;
        }

        public IEnumerable<WorkflowInstance> WorkflowInstances // r/o: No back-support to TrackableCollection
        {
            get => _instance.WorkflowInstances.Select(i => new WorkflowInstance(i));
            //set => _instance.WorkflowInstances = value.Select(i => i._instance); // ToTrackableCollection()
        }

        public IEnumerable<WorkflowActivityLog> WorkflowActivityLogs // r/o: No back-support to TrackableCollection
        {
            get => _instance.WorkflowActivityLogs.Select(i => new WorkflowActivityLog(i));
            //set => _instance.WorkflowActivityLogs = value.Select(i => i._instance); // ToTrackableCollection()
        }

    }
}
