//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Package))]
    [KnownType(typeof(PackageFolder))]
    [KnownType(typeof(PackageFolderFile))]
    public partial class PackageFolder: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid PackageFolderId
        {
            get { return _packageFolderId; }
            set
            {
                if (_packageFolderId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PackageFolderId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _packageFolderId = value;
                    OnPropertyChanged("PackageFolderId");
                }
            }
        }
        private System.Guid _packageFolderId;
    
        [DataMember]
        public System.Guid PackageId
        {
            get { return _packageId; }
            set
            {
                if (_packageId != value)
                {
                    ChangeTracker.RecordOriginalValue("PackageId", _packageId);
                    if (!IsDeserializing)
                    {
                        if (Package != null && Package.PackageId != value)
                        {
                            Package = null;
                        }
                    }
                    _packageId = value;
                    OnPropertyChanged("PackageId");
                }
            }
        }
        private System.Guid _packageId;
    
        [DataMember]
        public Nullable<System.Guid> ParentFolderId
        {
            get { return _parentFolderId; }
            set
            {
                if (_parentFolderId != value)
                {
                    ChangeTracker.RecordOriginalValue("ParentFolderId", _parentFolderId);
                    if (!IsDeserializing)
                    {
                        if (Parent != null && Parent.PackageFolderId != value)
                        {
                            Parent = null;
                        }
                    }
                    _parentFolderId = value;
                    OnPropertyChanged("ParentFolderId");
                }
            }
        }
        private Nullable<System.Guid> _parentFolderId;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public System.DateTime Modified
        {
            get { return _modified; }
            set
            {
                if (_modified != value)
                {
                    _modified = value;
                    OnPropertyChanged("Modified");
                }
            }
        }
        private System.DateTime _modified;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Package Package
        {
            get { return _package; }
            set
            {
                if (!ReferenceEquals(_package, value))
                {
                    var previousValue = _package;
                    _package = value;
                    FixupPackage(previousValue);
                    OnNavigationPropertyChanged("Package");
                }
            }
        }
        private Package _package;
    
        [DataMember]
        public TrackableCollection<PackageFolder> PackageFolders
        {
            get
            {
                if (_packageFolders == null)
                {
                    _packageFolders = new TrackableCollection<PackageFolder>();
                    _packageFolders.CollectionChanged += FixupPackageFolders;
                }
                return _packageFolders;
            }
            set
            {
                if (!ReferenceEquals(_packageFolders, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_packageFolders != null)
                    {
                        _packageFolders.CollectionChanged -= FixupPackageFolders;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (PackageFolder item in _packageFolders)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _packageFolders = value;
                    if (_packageFolders != null)
                    {
                        _packageFolders.CollectionChanged += FixupPackageFolders;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (PackageFolder item in _packageFolders)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("PackageFolders");
                }
            }
        }
        private TrackableCollection<PackageFolder> _packageFolders;
    
        [DataMember]
        public PackageFolder Parent
        {
            get { return _parent; }
            set
            {
                if (!ReferenceEquals(_parent, value))
                {
                    var previousValue = _parent;
                    _parent = value;
                    FixupParent(previousValue);
                    OnNavigationPropertyChanged("Parent");
                }
            }
        }
        private PackageFolder _parent;
    
        [DataMember]
        public TrackableCollection<PackageFolderFile> PackageFolderFiles
        {
            get
            {
                if (_packageFolderFiles == null)
                {
                    _packageFolderFiles = new TrackableCollection<PackageFolderFile>();
                    _packageFolderFiles.CollectionChanged += FixupPackageFolderFiles;
                }
                return _packageFolderFiles;
            }
            set
            {
                if (!ReferenceEquals(_packageFolderFiles, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_packageFolderFiles != null)
                    {
                        _packageFolderFiles.CollectionChanged -= FixupPackageFolderFiles;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (PackageFolderFile item in _packageFolderFiles)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _packageFolderFiles = value;
                    if (_packageFolderFiles != null)
                    {
                        _packageFolderFiles.CollectionChanged += FixupPackageFolderFiles;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (PackageFolderFile item in _packageFolderFiles)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("PackageFolderFiles");
                }
            }
        }
        private TrackableCollection<PackageFolderFile> _packageFolderFiles;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Package = null;
            PackageFolders.Clear();
            Parent = null;
            PackageFolderFiles.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupPackage(Package previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PackageFolders.Contains(this))
            {
                previousValue.PackageFolders.Remove(this);
            }
    
            if (Package != null)
            {
                if (!Package.PackageFolders.Contains(this))
                {
                    Package.PackageFolders.Add(this);
                }
    
                PackageId = Package.PackageId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Package")
                    && (ChangeTracker.OriginalValues["Package"] == Package))
                {
                    ChangeTracker.OriginalValues.Remove("Package");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Package", previousValue);
                }
                if (Package != null && !Package.ChangeTracker.ChangeTrackingEnabled)
                {
                    Package.StartTracking();
                }
            }
        }
    
        private void FixupParent(PackageFolder previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PackageFolders.Contains(this))
            {
                previousValue.PackageFolders.Remove(this);
            }
    
            if (Parent != null)
            {
                if (!Parent.PackageFolders.Contains(this))
                {
                    Parent.PackageFolders.Add(this);
                }
    
                ParentFolderId = Parent.PackageFolderId;
            }
            else if (!skipKeys)
            {
                ParentFolderId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Parent")
                    && (ChangeTracker.OriginalValues["Parent"] == Parent))
                {
                    ChangeTracker.OriginalValues.Remove("Parent");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Parent", previousValue);
                }
                if (Parent != null && !Parent.ChangeTracker.ChangeTrackingEnabled)
                {
                    Parent.StartTracking();
                }
            }
        }
    
        private void FixupPackageFolders(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PackageFolder item in e.NewItems)
                {
                    item.Parent = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PackageFolders", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PackageFolder item in e.OldItems)
                {
                    if (ReferenceEquals(item.Parent, this))
                    {
                        item.Parent = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PackageFolders", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }
    
        private void FixupPackageFolderFiles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PackageFolderFile item in e.NewItems)
                {
                    item.PackageFolder = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PackageFolderFiles", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PackageFolderFile item in e.OldItems)
                {
                    if (ReferenceEquals(item.PackageFolder, this))
                    {
                        item.PackageFolder = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PackageFolderFiles", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion

    }
}
