//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PackageFolder))]
    [KnownType(typeof(RepositoryFolderFile))]
    public partial class PackageFolderFile: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid PackageFolderFileId
        {
            get { return _packageFolderFileId; }
            set
            {
                if (_packageFolderFileId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PackageFolderFileId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _packageFolderFileId = value;
                    OnPropertyChanged("PackageFolderFileId");
                }
            }
        }
        private System.Guid _packageFolderFileId;
    
        [DataMember]
        public System.Guid PackageFolderId
        {
            get { return _packageFolderId; }
            set
            {
                if (_packageFolderId != value)
                {
                    ChangeTracker.RecordOriginalValue("PackageFolderId", _packageFolderId);
                    if (!IsDeserializing)
                    {
                        if (PackageFolder != null && PackageFolder.PackageFolderId != value)
                        {
                            PackageFolder = null;
                        }
                    }
                    _packageFolderId = value;
                    OnPropertyChanged("PackageFolderId");
                }
            }
        }
        private System.Guid _packageFolderId;
    
        [DataMember]
        public System.Guid RepositoryFolderFileId
        {
            get { return _repositoryFolderFileId; }
            set
            {
                if (_repositoryFolderFileId != value)
                {
                    ChangeTracker.RecordOriginalValue("RepositoryFolderFileId", _repositoryFolderFileId);
                    if (!IsDeserializing)
                    {
                        if (RepositoryFolderFile != null && RepositoryFolderFile.RepositoryFolderFileId != value)
                        {
                            RepositoryFolderFile = null;
                        }
                    }
                    _repositoryFolderFileId = value;
                    OnPropertyChanged("RepositoryFolderFileId");
                }
            }
        }
        private System.Guid _repositoryFolderFileId;
    
        [DataMember]
        public int Attributes
        {
            get { return _attributes; }
            set
            {
                if (_attributes != value)
                {
                    _attributes = value;
                    OnPropertyChanged("Attributes");
                }
            }
        }
        private int _attributes;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public PackageFolder PackageFolder
        {
            get { return _packageFolder; }
            set
            {
                if (!ReferenceEquals(_packageFolder, value))
                {
                    var previousValue = _packageFolder;
                    _packageFolder = value;
                    FixupPackageFolder(previousValue);
                    OnNavigationPropertyChanged("PackageFolder");
                }
            }
        }
        private PackageFolder _packageFolder;
    
        [DataMember]
        public RepositoryFolderFile RepositoryFolderFile
        {
            get { return _repositoryFolderFile; }
            set
            {
                if (!ReferenceEquals(_repositoryFolderFile, value))
                {
                    var previousValue = _repositoryFolderFile;
                    _repositoryFolderFile = value;
                    FixupRepositoryFolderFile(previousValue);
                    OnNavigationPropertyChanged("RepositoryFolderFile");
                }
            }
        }
        private RepositoryFolderFile _repositoryFolderFile;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PackageFolder = null;
            RepositoryFolderFile = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupPackageFolder(PackageFolder previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PackageFolderFiles.Contains(this))
            {
                previousValue.PackageFolderFiles.Remove(this);
            }
    
            if (PackageFolder != null)
            {
                if (!PackageFolder.PackageFolderFiles.Contains(this))
                {
                    PackageFolder.PackageFolderFiles.Add(this);
                }
    
                PackageFolderId = PackageFolder.PackageFolderId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PackageFolder")
                    && (ChangeTracker.OriginalValues["PackageFolder"] == PackageFolder))
                {
                    ChangeTracker.OriginalValues.Remove("PackageFolder");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PackageFolder", previousValue);
                }
                if (PackageFolder != null && !PackageFolder.ChangeTracker.ChangeTrackingEnabled)
                {
                    PackageFolder.StartTracking();
                }
            }
        }
    
        private void FixupRepositoryFolderFile(RepositoryFolderFile previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PackageFolderFiles.Contains(this))
            {
                previousValue.PackageFolderFiles.Remove(this);
            }
    
            if (RepositoryFolderFile != null)
            {
                if (!RepositoryFolderFile.PackageFolderFiles.Contains(this))
                {
                    RepositoryFolderFile.PackageFolderFiles.Add(this);
                }
    
                RepositoryFolderFileId = RepositoryFolderFile.RepositoryFolderFileId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("RepositoryFolderFile")
                    && (ChangeTracker.OriginalValues["RepositoryFolderFile"] == RepositoryFolderFile))
                {
                    ChangeTracker.OriginalValues.Remove("RepositoryFolderFile");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("RepositoryFolderFile", previousValue);
                }
                if (RepositoryFolderFile != null && !RepositoryFolderFile.ChangeTracker.ChangeTrackingEnabled)
                {
                    RepositoryFolderFile.StartTracking();
                }
            }
        }

        #endregion

    }
}
