//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Site))]
    [KnownType(typeof(Package))]
    public partial class PackageSiteRelation: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid PackageSiteRelationId
        {
            get { return _packageSiteRelationId; }
            set
            {
                if (_packageSiteRelationId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PackageSiteRelationId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _packageSiteRelationId = value;
                    OnPropertyChanged("PackageSiteRelationId");
                }
            }
        }
        private System.Guid _packageSiteRelationId;
    
        [DataMember]
        public System.Guid SiteId
        {
            get { return _siteId; }
            set
            {
                if (_siteId != value)
                {
                    ChangeTracker.RecordOriginalValue("SiteId", _siteId);
                    if (!IsDeserializing)
                    {
                        if (Site != null && Site.SiteId != value)
                        {
                            Site = null;
                        }
                    }
                    _siteId = value;
                    OnPropertyChanged("SiteId");
                }
            }
        }
        private System.Guid _siteId;
    
        [DataMember]
        public System.Guid PackageId
        {
            get { return _packageId; }
            set
            {
                if (_packageId != value)
                {
                    ChangeTracker.RecordOriginalValue("PackageId", _packageId);
                    if (!IsDeserializing)
                    {
                        if (Package != null && Package.PackageId != value)
                        {
                            Package = null;
                        }
                    }
                    _packageId = value;
                    OnPropertyChanged("PackageId");
                }
            }
        }
        private System.Guid _packageId;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Site Site
        {
            get { return _site; }
            set
            {
                if (!ReferenceEquals(_site, value))
                {
                    var previousValue = _site;
                    _site = value;
                    FixupSite(previousValue);
                    OnNavigationPropertyChanged("Site");
                }
            }
        }
        private Site _site;
    
        [DataMember]
        public Package Package
        {
            get { return _package; }
            set
            {
                if (!ReferenceEquals(_package, value))
                {
                    var previousValue = _package;
                    _package = value;
                    FixupPackage(previousValue);
                    OnNavigationPropertyChanged("Package");
                }
            }
        }
        private Package _package;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Site = null;
            Package = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupSite(Site previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PackageSiteRelations.Contains(this))
            {
                previousValue.PackageSiteRelations.Remove(this);
            }
    
            if (Site != null)
            {
                if (!Site.PackageSiteRelations.Contains(this))
                {
                    Site.PackageSiteRelations.Add(this);
                }
    
                SiteId = Site.SiteId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Site")
                    && (ChangeTracker.OriginalValues["Site"] == Site))
                {
                    ChangeTracker.OriginalValues.Remove("Site");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Site", previousValue);
                }
                if (Site != null && !Site.ChangeTracker.ChangeTrackingEnabled)
                {
                    Site.StartTracking();
                }
            }
        }
    
        private void FixupPackage(Package previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PackageSiteRelations.Contains(this))
            {
                previousValue.PackageSiteRelations.Remove(this);
            }
    
            if (Package != null)
            {
                if (!Package.PackageSiteRelations.Contains(this))
                {
                    Package.PackageSiteRelations.Add(this);
                }
    
                PackageId = Package.PackageId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Package")
                    && (ChangeTracker.OriginalValues["Package"] == Package))
                {
                    ChangeTracker.OriginalValues.Remove("Package");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Package", previousValue);
                }
                if (Package != null && !Package.ChangeTracker.ChangeTrackingEnabled)
                {
                    Package.StartTracking();
                }
            }
        }

        #endregion

    }
}
