//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Unit))]
    public partial class Process: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid ProcessId
        {
            get { return _processId; }
            set
            {
                if (_processId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ProcessId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _processId = value;
                    OnPropertyChanged("ProcessId");
                }
            }
        }
        private System.Guid _processId;
    
        [DataMember]
        public string Code
        {
            get { return _code; }
            set
            {
                if (_code != value)
                {
                    ChangeTracker.RecordOriginalValue("Code", _code);
                    _code = value;
                    OnPropertyChanged("Code");
                }
            }
        }
        private string _code;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    ChangeTracker.RecordOriginalValue("Name", _name);
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;
    
        [DataMember]
        public int ProcessIndex
        {
            get { return _processIndex; }
            set
            {
                if (_processIndex != value)
                {
                    _processIndex = value;
                    OnPropertyChanged("ProcessIndex");
                }
            }
        }
        private int _processIndex;
    
        [DataMember]
        public int State
        {
            get { return _state; }
            set
            {
                if (_state != value)
                {
                    _state = value;
                    OnPropertyChanged("State");
                }
            }
        }
        private int _state;
    
        [DataMember]
        public string Properties
        {
            get { return _properties; }
            set
            {
                if (_properties != value)
                {
                    _properties = value;
                    OnPropertyChanged("Properties");
                }
            }
        }
        private string _properties;
    
        [DataMember]
        public bool IsTestOperation
        {
            get { return _isTestOperation; }
            set
            {
                if (_isTestOperation != value)
                {
                    _isTestOperation = value;
                    OnPropertyChanged("IsTestOperation");
                }
            }
        }
        private bool _isTestOperation;
    
        [DataMember]
        public bool IsWIPOperation
        {
            get { return _isWIPOperation; }
            set
            {
                if (_isWIPOperation != value)
                {
                    _isWIPOperation = value;
                    OnPropertyChanged("IsWIPOperation");
                }
            }
        }
        private bool _isWIPOperation;
    
        [DataMember]
        public bool IsRepairOperation
        {
            get { return _isRepairOperation; }
            set
            {
                if (_isRepairOperation != value)
                {
                    _isRepairOperation = value;
                    OnPropertyChanged("IsRepairOperation");
                }
            }
        }
        private bool _isRepairOperation;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Unit> Units
        {
            get
            {
                if (_units == null)
                {
                    _units = new TrackableCollection<Unit>();
                    _units.CollectionChanged += FixupUnits;
                }
                return _units;
            }
            set
            {
                if (!ReferenceEquals(_units, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_units != null)
                    {
                        _units.CollectionChanged -= FixupUnits;
                    }
                    _units = value;
                    if (_units != null)
                    {
                        _units.CollectionChanged += FixupUnits;
                    }
                    OnNavigationPropertyChanged("Units");
                }
            }
        }
        private TrackableCollection<Unit> _units;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Units.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupUnits(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Unit item in e.NewItems)
                {
                    item.Process = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Units", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Unit item in e.OldItems)
                {
                    if (ReferenceEquals(item.Process, this))
                    {
                        item.Process = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Units", item);
                    }
                }
            }
        }

        #endregion

    }
}
