//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ProductRelation))]
    [KnownType(typeof(ProductRevision))]
    [KnownType(typeof(Unit))]
    [KnownType(typeof(ProductCategory))]
    [KnownType(typeof(Order))]
    public partial class Product: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid ProductId
        {
            get { return _productId; }
            set
            {
                if (_productId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ProductId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _productId = value;
                    OnPropertyChanged("ProductId");
                }
            }
        }
        private System.Guid _productId;
    
        [DataMember]
        public bool NonSerial
        {
            get { return _nonSerial; }
            set
            {
                if (_nonSerial != value)
                {
                    _nonSerial = value;
                    OnPropertyChanged("NonSerial");
                }
            }
        }
        private bool _nonSerial;
    
        [DataMember]
        public string PartNumber
        {
            get { return _partNumber; }
            set
            {
                if (_partNumber != value)
                {
                    _partNumber = value;
                    OnPropertyChanged("PartNumber");
                }
            }
        }
        private string _partNumber;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;
    
        [DataMember]
        public string XMLData
        {
            get { return _xMLData; }
            set
            {
                if (_xMLData != value)
                {
                    _xMLData = value;
                    OnPropertyChanged("XMLData");
                }
            }
        }
        private string _xMLData;
    
        [DataMember]
        public int State
        {
            get { return _state; }
            set
            {
                if (_state != value)
                {
                    _state = value;
                    OnPropertyChanged("State");
                }
            }
        }
        private int _state;
    
        [DataMember]
        public Nullable<System.Guid> ProductCategoryId
        {
            get { return _productCategoryId; }
            set
            {
                if (_productCategoryId != value)
                {
                    ChangeTracker.RecordOriginalValue("ProductCategoryId", _productCategoryId);
                    if (!IsDeserializing)
                    {
                        if (ProductCategory != null && ProductCategory.ProductCategoryId != value)
                        {
                            ProductCategory = null;
                        }
                    }
                    _productCategoryId = value;
                    OnPropertyChanged("ProductCategoryId");
                }
            }
        }
        private Nullable<System.Guid> _productCategoryId;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<ProductRelation> ChildProductRelations
        {
            get
            {
                if (_childProductRelations == null)
                {
                    _childProductRelations = new TrackableCollection<ProductRelation>();
                    _childProductRelations.CollectionChanged += FixupChildProductRelations;
                }
                return _childProductRelations;
            }
            set
            {
                if (!ReferenceEquals(_childProductRelations, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_childProductRelations != null)
                    {
                        _childProductRelations.CollectionChanged -= FixupChildProductRelations;
                    }
                    _childProductRelations = value;
                    if (_childProductRelations != null)
                    {
                        _childProductRelations.CollectionChanged += FixupChildProductRelations;
                    }
                    OnNavigationPropertyChanged("ChildProductRelations");
                }
            }
        }
        private TrackableCollection<ProductRelation> _childProductRelations;
    
        [DataMember]
        public TrackableCollection<ProductRelation> ParentProductRelations
        {
            get
            {
                if (_parentProductRelations == null)
                {
                    _parentProductRelations = new TrackableCollection<ProductRelation>();
                    _parentProductRelations.CollectionChanged += FixupParentProductRelations;
                }
                return _parentProductRelations;
            }
            set
            {
                if (!ReferenceEquals(_parentProductRelations, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_parentProductRelations != null)
                    {
                        _parentProductRelations.CollectionChanged -= FixupParentProductRelations;
                    }
                    _parentProductRelations = value;
                    if (_parentProductRelations != null)
                    {
                        _parentProductRelations.CollectionChanged += FixupParentProductRelations;
                    }
                    OnNavigationPropertyChanged("ParentProductRelations");
                }
            }
        }
        private TrackableCollection<ProductRelation> _parentProductRelations;
    
        [DataMember]
        public TrackableCollection<ProductRevision> ProductRevisions
        {
            get
            {
                if (_productRevisions == null)
                {
                    _productRevisions = new TrackableCollection<ProductRevision>();
                    _productRevisions.CollectionChanged += FixupProductRevisions;
                }
                return _productRevisions;
            }
            set
            {
                if (!ReferenceEquals(_productRevisions, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_productRevisions != null)
                    {
                        _productRevisions.CollectionChanged -= FixupProductRevisions;
                    }
                    _productRevisions = value;
                    if (_productRevisions != null)
                    {
                        _productRevisions.CollectionChanged += FixupProductRevisions;
                    }
                    OnNavigationPropertyChanged("ProductRevisions");
                }
            }
        }
        private TrackableCollection<ProductRevision> _productRevisions;
    
        [DataMember]
        public TrackableCollection<Unit> Units
        {
            get
            {
                if (_units == null)
                {
                    _units = new TrackableCollection<Unit>();
                    _units.CollectionChanged += FixupUnits;
                }
                return _units;
            }
            set
            {
                if (!ReferenceEquals(_units, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_units != null)
                    {
                        _units.CollectionChanged -= FixupUnits;
                    }
                    _units = value;
                    if (_units != null)
                    {
                        _units.CollectionChanged += FixupUnits;
                    }
                    OnNavigationPropertyChanged("Units");
                }
            }
        }
        private TrackableCollection<Unit> _units;
    
        [DataMember]
        public ProductCategory ProductCategory
        {
            get { return _productCategory; }
            set
            {
                if (!ReferenceEquals(_productCategory, value))
                {
                    var previousValue = _productCategory;
                    _productCategory = value;
                    FixupProductCategory(previousValue);
                    OnNavigationPropertyChanged("ProductCategory");
                }
            }
        }
        private ProductCategory _productCategory;
    
        [DataMember]
        public TrackableCollection<Order> Orders
        {
            get
            {
                if (_orders == null)
                {
                    _orders = new TrackableCollection<Order>();
                    _orders.CollectionChanged += FixupOrders;
                }
                return _orders;
            }
            set
            {
                if (!ReferenceEquals(_orders, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_orders != null)
                    {
                        _orders.CollectionChanged -= FixupOrders;
                    }
                    _orders = value;
                    if (_orders != null)
                    {
                        _orders.CollectionChanged += FixupOrders;
                    }
                    OnNavigationPropertyChanged("Orders");
                }
            }
        }
        private TrackableCollection<Order> _orders;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ChildProductRelations.Clear();
            ParentProductRelations.Clear();
            ProductRevisions.Clear();
            Units.Clear();
            ProductCategory = null;
            Orders.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupProductCategory(ProductCategory previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Products.Contains(this))
            {
                previousValue.Products.Remove(this);
            }
    
            if (ProductCategory != null)
            {
                if (!ProductCategory.Products.Contains(this))
                {
                    ProductCategory.Products.Add(this);
                }
    
                ProductCategoryId = ProductCategory.ProductCategoryId;
            }
            else if (!skipKeys)
            {
                ProductCategoryId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ProductCategory")
                    && (ChangeTracker.OriginalValues["ProductCategory"] == ProductCategory))
                {
                    ChangeTracker.OriginalValues.Remove("ProductCategory");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ProductCategory", previousValue);
                }
                if (ProductCategory != null && !ProductCategory.ChangeTracker.ChangeTrackingEnabled)
                {
                    ProductCategory.StartTracking();
                }
            }
        }
    
        private void FixupChildProductRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ProductRelation item in e.NewItems)
                {
                    item.ParentProduct = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ChildProductRelations", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductRelation item in e.OldItems)
                {
                    if (ReferenceEquals(item.ParentProduct, this))
                    {
                        item.ParentProduct = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ChildProductRelations", item);
                    }
                }
            }
        }
    
        private void FixupParentProductRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ProductRelation item in e.NewItems)
                {
                    item.ChildProduct = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ParentProductRelations", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductRelation item in e.OldItems)
                {
                    if (ReferenceEquals(item.ChildProduct, this))
                    {
                        item.ChildProduct = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ParentProductRelations", item);
                    }
                }
            }
        }
    
        private void FixupProductRevisions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ProductRevision item in e.NewItems)
                {
                    item.Product = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ProductRevisions", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductRevision item in e.OldItems)
                {
                    if (ReferenceEquals(item.Product, this))
                    {
                        item.Product = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ProductRevisions", item);
                    }
                }
            }
        }
    
        private void FixupUnits(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Unit item in e.NewItems)
                {
                    item.Product = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Units", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Unit item in e.OldItems)
                {
                    if (ReferenceEquals(item.Product, this))
                    {
                        item.Product = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Units", item);
                    }
                }
            }
        }
    
        private void FixupOrders(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Order item in e.NewItems)
                {
                    item.Product = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Orders", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Order item in e.OldItems)
                {
                    if (ReferenceEquals(item.Product, this))
                    {
                        item.Product = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Orders", item);
                    }
                }
            }
        }

        #endregion

    }
}
