//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Product))]
    [KnownType(typeof(Unit))]
    [KnownType(typeof(ProductRevisionRelation))]
    [KnownType(typeof(Order))]
    public partial class ProductRevision: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid ProductRevisionId
        {
            get { return _productRevisionId; }
            set
            {
                if (_productRevisionId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ProductRevisionId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _productRevisionId = value;
                    OnPropertyChanged("ProductRevisionId");
                }
            }
        }
        private System.Guid _productRevisionId;
    
        [DataMember]
        public System.Guid ProductId
        {
            get { return _productId; }
            set
            {
                if (_productId != value)
                {
                    ChangeTracker.RecordOriginalValue("ProductId", _productId);
                    if (!IsDeserializing)
                    {
                        if (Product != null && Product.ProductId != value)
                        {
                            Product = null;
                        }
                    }
                    _productId = value;
                    OnPropertyChanged("ProductId");
                }
            }
        }
        private System.Guid _productId;
    
        [DataMember]
        public string Revision
        {
            get { return _revision; }
            set
            {
                if (_revision != value)
                {
                    _revision = value;
                    OnPropertyChanged("Revision");
                }
            }
        }
        private string _revision;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;
    
        [DataMember]
        public string XMLData
        {
            get { return _xMLData; }
            set
            {
                if (_xMLData != value)
                {
                    _xMLData = value;
                    OnPropertyChanged("XMLData");
                }
            }
        }
        private string _xMLData;
    
        [DataMember]
        public int State
        {
            get { return _state; }
            set
            {
                if (_state != value)
                {
                    _state = value;
                    OnPropertyChanged("State");
                }
            }
        }
        private int _state;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Product Product
        {
            get { return _product; }
            set
            {
                if (!ReferenceEquals(_product, value))
                {
                    var previousValue = _product;
                    _product = value;
                    FixupProduct(previousValue);
                    OnNavigationPropertyChanged("Product");
                }
            }
        }
        private Product _product;
    
        [DataMember]
        public TrackableCollection<Unit> Units
        {
            get
            {
                if (_units == null)
                {
                    _units = new TrackableCollection<Unit>();
                    _units.CollectionChanged += FixupUnits;
                }
                return _units;
            }
            set
            {
                if (!ReferenceEquals(_units, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_units != null)
                    {
                        _units.CollectionChanged -= FixupUnits;
                    }
                    _units = value;
                    if (_units != null)
                    {
                        _units.CollectionChanged += FixupUnits;
                    }
                    OnNavigationPropertyChanged("Units");
                }
            }
        }
        private TrackableCollection<Unit> _units;
    
        [DataMember]
        public TrackableCollection<ProductRevisionRelation> ChildProductRevisionRelations
        {
            get
            {
                if (_childProductRevisionRelations == null)
                {
                    _childProductRevisionRelations = new TrackableCollection<ProductRevisionRelation>();
                    _childProductRevisionRelations.CollectionChanged += FixupChildProductRevisionRelations;
                }
                return _childProductRevisionRelations;
            }
            set
            {
                if (!ReferenceEquals(_childProductRevisionRelations, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_childProductRevisionRelations != null)
                    {
                        _childProductRevisionRelations.CollectionChanged -= FixupChildProductRevisionRelations;
                    }
                    _childProductRevisionRelations = value;
                    if (_childProductRevisionRelations != null)
                    {
                        _childProductRevisionRelations.CollectionChanged += FixupChildProductRevisionRelations;
                    }
                    OnNavigationPropertyChanged("ChildProductRevisionRelations");
                }
            }
        }
        private TrackableCollection<ProductRevisionRelation> _childProductRevisionRelations;
    
        [DataMember]
        public TrackableCollection<ProductRevisionRelation> ParentProductRevisionRelations
        {
            get
            {
                if (_parentProductRevisionRelations == null)
                {
                    _parentProductRevisionRelations = new TrackableCollection<ProductRevisionRelation>();
                    _parentProductRevisionRelations.CollectionChanged += FixupParentProductRevisionRelations;
                }
                return _parentProductRevisionRelations;
            }
            set
            {
                if (!ReferenceEquals(_parentProductRevisionRelations, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_parentProductRevisionRelations != null)
                    {
                        _parentProductRevisionRelations.CollectionChanged -= FixupParentProductRevisionRelations;
                    }
                    _parentProductRevisionRelations = value;
                    if (_parentProductRevisionRelations != null)
                    {
                        _parentProductRevisionRelations.CollectionChanged += FixupParentProductRevisionRelations;
                    }
                    OnNavigationPropertyChanged("ParentProductRevisionRelations");
                }
            }
        }
        private TrackableCollection<ProductRevisionRelation> _parentProductRevisionRelations;
    
        [DataMember]
        public TrackableCollection<Order> Orders
        {
            get
            {
                if (_orders == null)
                {
                    _orders = new TrackableCollection<Order>();
                    _orders.CollectionChanged += FixupOrders;
                }
                return _orders;
            }
            set
            {
                if (!ReferenceEquals(_orders, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_orders != null)
                    {
                        _orders.CollectionChanged -= FixupOrders;
                    }
                    _orders = value;
                    if (_orders != null)
                    {
                        _orders.CollectionChanged += FixupOrders;
                    }
                    OnNavigationPropertyChanged("Orders");
                }
            }
        }
        private TrackableCollection<Order> _orders;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Product = null;
            Units.Clear();
            ChildProductRevisionRelations.Clear();
            ParentProductRevisionRelations.Clear();
            Orders.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupProduct(Product previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ProductRevisions.Contains(this))
            {
                previousValue.ProductRevisions.Remove(this);
            }
    
            if (Product != null)
            {
                if (!Product.ProductRevisions.Contains(this))
                {
                    Product.ProductRevisions.Add(this);
                }
    
                ProductId = Product.ProductId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Product")
                    && (ChangeTracker.OriginalValues["Product"] == Product))
                {
                    ChangeTracker.OriginalValues.Remove("Product");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Product", previousValue);
                }
                if (Product != null && !Product.ChangeTracker.ChangeTrackingEnabled)
                {
                    Product.StartTracking();
                }
            }
        }
    
        private void FixupUnits(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Unit item in e.NewItems)
                {
                    item.ProductRevision = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Units", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Unit item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductRevision, this))
                    {
                        item.ProductRevision = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Units", item);
                    }
                }
            }
        }
    
        private void FixupChildProductRevisionRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ProductRevisionRelation item in e.NewItems)
                {
                    item.ParentProductRevision = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ChildProductRevisionRelations", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductRevisionRelation item in e.OldItems)
                {
                    if (ReferenceEquals(item.ParentProductRevision, this))
                    {
                        item.ParentProductRevision = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ChildProductRevisionRelations", item);
                    }
                }
            }
        }
    
        private void FixupParentProductRevisionRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ProductRevisionRelation item in e.NewItems)
                {
                    item.ChildProductRevision = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ParentProductRevisionRelations", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductRevisionRelation item in e.OldItems)
                {
                    if (ReferenceEquals(item.ChildProductRevision, this))
                    {
                        item.ChildProductRevision = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ParentProductRevisionRelations", item);
                    }
                }
            }
        }
    
        private void FixupOrders(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Order item in e.NewItems)
                {
                    item.ProductRevision = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Orders", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Order item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductRevision, this))
                    {
                        item.ProductRevision = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Orders", item);
                    }
                }
            }
        }

        #endregion

    }
}
