//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Site))]
    [KnownType(typeof(Status))]
    [KnownType(typeof(VirtualFolder))]
    [KnownType(typeof(TestSequenceDefinitionXaml))]
    [KnownType(typeof(TestSequenceInstance))]
    [KnownType(typeof(TestSequenceRelation))]
    [KnownType(typeof(TestSequenceDefinitionMedia))]
    public partial class TestSequenceDefinition: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid TestSequenceDefinitionId
        {
            get { return _testSequenceDefinitionId; }
            set
            {
                if (_testSequenceDefinitionId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'TestSequenceDefinitionId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _testSequenceDefinitionId = value;
                    OnPropertyChanged("TestSequenceDefinitionId");
                }
            }
        }
        private System.Guid _testSequenceDefinitionId;
    
        [DataMember]
        public System.Guid VirtualFolderId
        {
            get { return _virtualFolderId; }
            set
            {
                if (_virtualFolderId != value)
                {
                    ChangeTracker.RecordOriginalValue("VirtualFolderId", _virtualFolderId);
                    if (!IsDeserializing)
                    {
                        if (VirtualFolder != null && VirtualFolder.VirtualFolderId != value)
                        {
                            VirtualFolder = null;
                        }
                    }
                    _virtualFolderId = value;
                    OnPropertyChanged("VirtualFolderId");
                }
            }
        }
        private System.Guid _virtualFolderId;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public int Version
        {
            get { return _version; }
            set
            {
                if (_version != value)
                {
                    _version = value;
                    OnPropertyChanged("Version");
                }
            }
        }
        private int _version;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;
    
        [DataMember]
        public System.DateTime Created
        {
            get { return _created; }
            set
            {
                if (_created != value)
                {
                    _created = value;
                    OnPropertyChanged("Created");
                }
            }
        }
        private System.DateTime _created;
    
        [DataMember]
        public string CreatedBy
        {
            get { return _createdBy; }
            set
            {
                if (_createdBy != value)
                {
                    _createdBy = value;
                    OnPropertyChanged("CreatedBy");
                }
            }
        }
        private string _createdBy;
    
        [DataMember]
        public System.Guid CreatedBySiteId
        {
            get { return _createdBySiteId; }
            set
            {
                if (_createdBySiteId != value)
                {
                    ChangeTracker.RecordOriginalValue("CreatedBySiteId", _createdBySiteId);
                    if (!IsDeserializing)
                    {
                        if (Site != null && Site.SiteId != value)
                        {
                            Site = null;
                        }
                    }
                    _createdBySiteId = value;
                    OnPropertyChanged("CreatedBySiteId");
                }
            }
        }
        private System.Guid _createdBySiteId;
    
        [DataMember]
        public Nullable<System.DateTime> Released
        {
            get { return _released; }
            set
            {
                if (_released != value)
                {
                    _released = value;
                    OnPropertyChanged("Released");
                }
            }
        }
        private Nullable<System.DateTime> _released;
    
        [DataMember]
        public string ReleasedBy
        {
            get { return _releasedBy; }
            set
            {
                if (_releasedBy != value)
                {
                    _releasedBy = value;
                    OnPropertyChanged("ReleasedBy");
                }
            }
        }
        private string _releasedBy;
    
        [DataMember]
        public int Status
        {
            get { return _status; }
            set
            {
                if (_status != value)
                {
                    ChangeTracker.RecordOriginalValue("Status", _status);
                    if (!IsDeserializing)
                    {
                        if (Status1 != null && Status1.StatusId != value)
                        {
                            Status1 = null;
                        }
                    }
                    _status = value;
                    OnPropertyChanged("Status");
                }
            }
        }
        private int _status;
    
        [DataMember]
        public bool IsGlobal
        {
            get { return _isGlobal; }
            set
            {
                if (_isGlobal != value)
                {
                    _isGlobal = value;
                    OnPropertyChanged("IsGlobal");
                }
            }
        }
        private bool _isGlobal;
    
        [DataMember]
        public bool OnFailGotoCleanup
        {
            get { return _onFailGotoCleanup; }
            set
            {
                if (_onFailGotoCleanup != value)
                {
                    _onFailGotoCleanup = value;
                    OnPropertyChanged("OnFailGotoCleanup");
                }
            }
        }
        private bool _onFailGotoCleanup;
    
        [DataMember]
        public bool OnFailRequireSubmit
        {
            get { return _onFailRequireSubmit; }
            set
            {
                if (_onFailRequireSubmit != value)
                {
                    _onFailRequireSubmit = value;
                    OnPropertyChanged("OnFailRequireSubmit");
                }
            }
        }
        private bool _onFailRequireSubmit;
    
        [DataMember]
        public Nullable<System.Guid> RepairProcessId
        {
            get { return _repairProcessId; }
            set
            {
                if (_repairProcessId != value)
                {
                    _repairProcessId = value;
                    OnPropertyChanged("RepairProcessId");
                }
            }
        }
        private Nullable<System.Guid> _repairProcessId;
    
        [DataMember]
        public byte OnFailRequireRepair
        {
            get { return _onFailRequireRepair; }
            set
            {
                if (_onFailRequireRepair != value)
                {
                    _onFailRequireRepair = value;
                    OnPropertyChanged("OnFailRequireRepair");
                }
            }
        }
        private byte _onFailRequireRepair;
    
        [DataMember]
        public bool AddChildUnits
        {
            get { return _addChildUnits; }
            set
            {
                if (_addChildUnits != value)
                {
                    _addChildUnits = value;
                    OnPropertyChanged("AddChildUnits");
                }
            }
        }
        private bool _addChildUnits;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Site Site
        {
            get { return _site; }
            set
            {
                if (!ReferenceEquals(_site, value))
                {
                    var previousValue = _site;
                    _site = value;
                    FixupSite(previousValue);
                    OnNavigationPropertyChanged("Site");
                }
            }
        }
        private Site _site;
    
        [DataMember]
        public Status Status1
        {
            get { return _status1; }
            set
            {
                if (!ReferenceEquals(_status1, value))
                {
                    var previousValue = _status1;
                    _status1 = value;
                    FixupStatus1(previousValue);
                    OnNavigationPropertyChanged("Status1");
                }
            }
        }
        private Status _status1;
    
        [DataMember]
        public VirtualFolder VirtualFolder
        {
            get { return _virtualFolder; }
            set
            {
                if (!ReferenceEquals(_virtualFolder, value))
                {
                    var previousValue = _virtualFolder;
                    _virtualFolder = value;
                    FixupVirtualFolder(previousValue);
                    OnNavigationPropertyChanged("VirtualFolder");
                }
            }
        }
        private VirtualFolder _virtualFolder;
    
        [DataMember]
        public TestSequenceDefinitionXaml TestSequenceDefinitionXaml
        {
            get { return _testSequenceDefinitionXaml; }
            set
            {
                if (!ReferenceEquals(_testSequenceDefinitionXaml, value))
                {
                    var previousValue = _testSequenceDefinitionXaml;
                    _testSequenceDefinitionXaml = value;
                    FixupTestSequenceDefinitionXaml(previousValue);
                    OnNavigationPropertyChanged("TestSequenceDefinitionXaml");
                }
            }
        }
        private TestSequenceDefinitionXaml _testSequenceDefinitionXaml;
    
        [DataMember]
        public TrackableCollection<TestSequenceInstance> TestSequenceInstances
        {
            get
            {
                if (_testSequenceInstances == null)
                {
                    _testSequenceInstances = new TrackableCollection<TestSequenceInstance>();
                    _testSequenceInstances.CollectionChanged += FixupTestSequenceInstances;
                }
                return _testSequenceInstances;
            }
            set
            {
                if (!ReferenceEquals(_testSequenceInstances, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_testSequenceInstances != null)
                    {
                        _testSequenceInstances.CollectionChanged -= FixupTestSequenceInstances;
                    }
                    _testSequenceInstances = value;
                    if (_testSequenceInstances != null)
                    {
                        _testSequenceInstances.CollectionChanged += FixupTestSequenceInstances;
                    }
                    OnNavigationPropertyChanged("TestSequenceInstances");
                }
            }
        }
        private TrackableCollection<TestSequenceInstance> _testSequenceInstances;
    
        [DataMember]
        public TrackableCollection<TestSequenceRelation> TestSequenceRelations
        {
            get
            {
                if (_testSequenceRelations == null)
                {
                    _testSequenceRelations = new TrackableCollection<TestSequenceRelation>();
                    _testSequenceRelations.CollectionChanged += FixupTestSequenceRelations;
                }
                return _testSequenceRelations;
            }
            set
            {
                if (!ReferenceEquals(_testSequenceRelations, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_testSequenceRelations != null)
                    {
                        _testSequenceRelations.CollectionChanged -= FixupTestSequenceRelations;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (TestSequenceRelation item in _testSequenceRelations)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _testSequenceRelations = value;
                    if (_testSequenceRelations != null)
                    {
                        _testSequenceRelations.CollectionChanged += FixupTestSequenceRelations;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (TestSequenceRelation item in _testSequenceRelations)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("TestSequenceRelations");
                }
            }
        }
        private TrackableCollection<TestSequenceRelation> _testSequenceRelations;
    
        [DataMember]
        public TrackableCollection<TestSequenceDefinitionMedia> TestSequenceDefinitionMedias
        {
            get
            {
                if (_testSequenceDefinitionMedias == null)
                {
                    _testSequenceDefinitionMedias = new TrackableCollection<TestSequenceDefinitionMedia>();
                    _testSequenceDefinitionMedias.CollectionChanged += FixupTestSequenceDefinitionMedias;
                }
                return _testSequenceDefinitionMedias;
            }
            set
            {
                if (!ReferenceEquals(_testSequenceDefinitionMedias, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_testSequenceDefinitionMedias != null)
                    {
                        _testSequenceDefinitionMedias.CollectionChanged -= FixupTestSequenceDefinitionMedias;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (TestSequenceDefinitionMedia item in _testSequenceDefinitionMedias)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _testSequenceDefinitionMedias = value;
                    if (_testSequenceDefinitionMedias != null)
                    {
                        _testSequenceDefinitionMedias.CollectionChanged += FixupTestSequenceDefinitionMedias;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (TestSequenceDefinitionMedia item in _testSequenceDefinitionMedias)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("TestSequenceDefinitionMedias");
                }
            }
        }
        private TrackableCollection<TestSequenceDefinitionMedia> _testSequenceDefinitionMedias;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Site = null;
            Status1 = null;
            VirtualFolder = null;
            TestSequenceDefinitionXaml = null;
            TestSequenceInstances.Clear();
            TestSequenceRelations.Clear();
            TestSequenceDefinitionMedias.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupSite(Site previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TestSequenceDefinitions.Contains(this))
            {
                previousValue.TestSequenceDefinitions.Remove(this);
            }
    
            if (Site != null)
            {
                if (!Site.TestSequenceDefinitions.Contains(this))
                {
                    Site.TestSequenceDefinitions.Add(this);
                }
    
                CreatedBySiteId = Site.SiteId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Site")
                    && (ChangeTracker.OriginalValues["Site"] == Site))
                {
                    ChangeTracker.OriginalValues.Remove("Site");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Site", previousValue);
                }
                if (Site != null && !Site.ChangeTracker.ChangeTrackingEnabled)
                {
                    Site.StartTracking();
                }
            }
        }
    
        private void FixupStatus1(Status previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TestSequenceDefinitions.Contains(this))
            {
                previousValue.TestSequenceDefinitions.Remove(this);
            }
    
            if (Status1 != null)
            {
                if (!Status1.TestSequenceDefinitions.Contains(this))
                {
                    Status1.TestSequenceDefinitions.Add(this);
                }
    
                Status = Status1.StatusId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Status1")
                    && (ChangeTracker.OriginalValues["Status1"] == Status1))
                {
                    ChangeTracker.OriginalValues.Remove("Status1");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Status1", previousValue);
                }
                if (Status1 != null && !Status1.ChangeTracker.ChangeTrackingEnabled)
                {
                    Status1.StartTracking();
                }
            }
        }
    
        private void FixupVirtualFolder(VirtualFolder previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TestSequenceDefinitions.Contains(this))
            {
                previousValue.TestSequenceDefinitions.Remove(this);
            }
    
            if (VirtualFolder != null)
            {
                if (!VirtualFolder.TestSequenceDefinitions.Contains(this))
                {
                    VirtualFolder.TestSequenceDefinitions.Add(this);
                }
    
                VirtualFolderId = VirtualFolder.VirtualFolderId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("VirtualFolder")
                    && (ChangeTracker.OriginalValues["VirtualFolder"] == VirtualFolder))
                {
                    ChangeTracker.OriginalValues.Remove("VirtualFolder");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("VirtualFolder", previousValue);
                }
                if (VirtualFolder != null && !VirtualFolder.ChangeTracker.ChangeTrackingEnabled)
                {
                    VirtualFolder.StartTracking();
                }
            }
        }
    
        private void FixupTestSequenceDefinitionXaml(TestSequenceDefinitionXaml previousValue)
        {
            // This is the principal end in an association that performs cascade deletes.
            // Update the event listener to refer to the new dependent.
            if (previousValue != null)
            {
                ChangeTracker.ObjectStateChanging -= previousValue.HandleCascadeDelete;
            }
    
            if (TestSequenceDefinitionXaml != null)
            {
                ChangeTracker.ObjectStateChanging += TestSequenceDefinitionXaml.HandleCascadeDelete;
            }
    
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.TestSequenceDefinition, this))
            {
                previousValue.TestSequenceDefinition = null;
            }
    
            if (TestSequenceDefinitionXaml != null)
            {
                TestSequenceDefinitionXaml.TestSequenceDefinition = this;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TestSequenceDefinitionXaml")
                    && (ChangeTracker.OriginalValues["TestSequenceDefinitionXaml"] == TestSequenceDefinitionXaml))
                {
                    ChangeTracker.OriginalValues.Remove("TestSequenceDefinitionXaml");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TestSequenceDefinitionXaml", previousValue);
                    // This is the principal end of an identifying association, so the dependent must be deleted when the relationship is removed.
                    // If the current state of the dependent is Added, the relationship can be changed without causing the dependent to be deleted.
                    if (previousValue != null && previousValue.ChangeTracker.State != ObjectState.Added)
                    {
                        previousValue.MarkAsDeleted();
                    }
                }
                if (TestSequenceDefinitionXaml != null && !TestSequenceDefinitionXaml.ChangeTracker.ChangeTrackingEnabled)
                {
                    TestSequenceDefinitionXaml.StartTracking();
                }
            }
        }
    
        private void FixupTestSequenceInstances(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TestSequenceInstance item in e.NewItems)
                {
                    item.TestSequenceDefinition = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TestSequenceInstances", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TestSequenceInstance item in e.OldItems)
                {
                    if (ReferenceEquals(item.TestSequenceDefinition, this))
                    {
                        item.TestSequenceDefinition = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TestSequenceInstances", item);
                    }
                }
            }
        }
    
        private void FixupTestSequenceRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TestSequenceRelation item in e.NewItems)
                {
                    item.TestSequenceDefinition = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TestSequenceRelations", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TestSequenceRelation item in e.OldItems)
                {
                    if (ReferenceEquals(item.TestSequenceDefinition, this))
                    {
                        item.TestSequenceDefinition = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TestSequenceRelations", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }
    
        private void FixupTestSequenceDefinitionMedias(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TestSequenceDefinitionMedia item in e.NewItems)
                {
                    item.TestSequenceDefinition = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TestSequenceDefinitionMedias", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TestSequenceDefinitionMedia item in e.OldItems)
                {
                    if (ReferenceEquals(item.TestSequenceDefinition, this))
                    {
                        item.TestSequenceDefinition = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TestSequenceDefinitionMedias", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion

    }
}
