//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(TestSequenceDefinition))]
    public partial class TestSequenceInstance: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid TestSequenceInstanceId
        {
            get { return _testSequenceInstanceId; }
            set
            {
                if (_testSequenceInstanceId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'TestSequenceInstanceId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _testSequenceInstanceId = value;
                    OnPropertyChanged("TestSequenceInstanceId");
                }
            }
        }
        private System.Guid _testSequenceInstanceId;
    
        [DataMember]
        public System.Guid TestSequenceDefinitionId
        {
            get { return _testSequenceDefinitionId; }
            set
            {
                if (_testSequenceDefinitionId != value)
                {
                    ChangeTracker.RecordOriginalValue("TestSequenceDefinitionId", _testSequenceDefinitionId);
                    if (!IsDeserializing)
                    {
                        if (TestSequenceDefinition != null && TestSequenceDefinition.TestSequenceDefinitionId != value)
                        {
                            TestSequenceDefinition = null;
                        }
                    }
                    _testSequenceDefinitionId = value;
                    OnPropertyChanged("TestSequenceDefinitionId");
                }
            }
        }
        private System.Guid _testSequenceDefinitionId;
    
        [DataMember]
        public Nullable<System.Guid> UnitId
        {
            get { return _unitId; }
            set
            {
                if (_unitId != value)
                {
                    _unitId = value;
                    OnPropertyChanged("UnitId");
                }
            }
        }
        private Nullable<System.Guid> _unitId;
    
        [DataMember]
        public string SerialNumber
        {
            get { return _serialNumber; }
            set
            {
                if (_serialNumber != value)
                {
                    _serialNumber = value;
                    OnPropertyChanged("SerialNumber");
                }
            }
        }
        private string _serialNumber;
    
        [DataMember]
        public string PartNumber
        {
            get { return _partNumber; }
            set
            {
                if (_partNumber != value)
                {
                    _partNumber = value;
                    OnPropertyChanged("PartNumber");
                }
            }
        }
        private string _partNumber;
    
        [DataMember]
        public string Revision
        {
            get { return _revision; }
            set
            {
                if (_revision != value)
                {
                    _revision = value;
                    OnPropertyChanged("Revision");
                }
            }
        }
        private string _revision;
    
        [DataMember]
        public System.DateTime Created
        {
            get { return _created; }
            set
            {
                if (_created != value)
                {
                    _created = value;
                    OnPropertyChanged("Created");
                }
            }
        }
        private System.DateTime _created;
    
        [DataMember]
        public System.DateTime LastEventTime
        {
            get { return _lastEventTime; }
            set
            {
                if (_lastEventTime != value)
                {
                    _lastEventTime = value;
                    OnPropertyChanged("LastEventTime");
                }
            }
        }
        private System.DateTime _lastEventTime;
    
        [DataMember]
        public string Instance
        {
            get { return _instance; }
            set
            {
                if (_instance != value)
                {
                    _instance = value;
                    OnPropertyChanged("Instance");
                }
            }
        }
        private string _instance;
    
        [DataMember]
        public Nullable<System.Guid> ProcessId
        {
            get { return _processId; }
            set
            {
                if (_processId != value)
                {
                    _processId = value;
                    OnPropertyChanged("ProcessId");
                }
            }
        }
        private Nullable<System.Guid> _processId;
    
        [DataMember]
        public Nullable<System.Guid> RepairProcessId
        {
            get { return _repairProcessId; }
            set
            {
                if (_repairProcessId != value)
                {
                    _repairProcessId = value;
                    OnPropertyChanged("RepairProcessId");
                }
            }
        }
        private Nullable<System.Guid> _repairProcessId;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TestSequenceDefinition TestSequenceDefinition
        {
            get { return _testSequenceDefinition; }
            set
            {
                if (!ReferenceEquals(_testSequenceDefinition, value))
                {
                    var previousValue = _testSequenceDefinition;
                    _testSequenceDefinition = value;
                    FixupTestSequenceDefinition(previousValue);
                    OnNavigationPropertyChanged("TestSequenceDefinition");
                }
            }
        }
        private TestSequenceDefinition _testSequenceDefinition;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            TestSequenceDefinition = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupTestSequenceDefinition(TestSequenceDefinition previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TestSequenceInstances.Contains(this))
            {
                previousValue.TestSequenceInstances.Remove(this);
            }
    
            if (TestSequenceDefinition != null)
            {
                if (!TestSequenceDefinition.TestSequenceInstances.Contains(this))
                {
                    TestSequenceDefinition.TestSequenceInstances.Add(this);
                }
    
                TestSequenceDefinitionId = TestSequenceDefinition.TestSequenceDefinitionId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TestSequenceDefinition")
                    && (ChangeTracker.OriginalValues["TestSequenceDefinition"] == TestSequenceDefinition))
                {
                    ChangeTracker.OriginalValues.Remove("TestSequenceDefinition");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TestSequenceDefinition", previousValue);
                }
                if (TestSequenceDefinition != null && !TestSequenceDefinition.ChangeTracker.ChangeTrackingEnabled)
                {
                    TestSequenceDefinition.StartTracking();
                }
            }
        }

        #endregion

    }
}
