//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Site))]
    [KnownType(typeof(ProductRevision))]
    [KnownType(typeof(ProductionBatch))]
    [KnownType(typeof(Unit))]
    [KnownType(typeof(WorkflowInstance))]
    [KnownType(typeof(UnitPhase))]
    [KnownType(typeof(Product))]
    [KnownType(typeof(Process))]
    [KnownType(typeof(Order))]
    public partial class Unit: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid UnitId
        {
            get { return _unitId; }
            set
            {
                if (_unitId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'UnitId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _unitId = value;
                    OnPropertyChanged("UnitId");
                }
            }
        }
        private System.Guid _unitId;
    
        [DataMember]
        public Nullable<System.Guid> ParentUnitId
        {
            get { return _parentUnitId; }
            set
            {
                if (_parentUnitId != value)
                {
                    ChangeTracker.RecordOriginalValue("ParentUnitId", _parentUnitId);
                    if (!IsDeserializing)
                    {
                        if (Parent != null && Parent.UnitId != value)
                        {
                            Parent = null;
                        }
                    }
                    _parentUnitId = value;
                    OnPropertyChanged("ParentUnitId");
                }
            }
        }
        private Nullable<System.Guid> _parentUnitId;
    
        [DataMember]
        public System.Guid ProductRevisionId
        {
            get { return _productRevisionId; }
            set
            {
                if (_productRevisionId != value)
                {
                    ChangeTracker.RecordOriginalValue("ProductRevisionId", _productRevisionId);
                    if (!IsDeserializing)
                    {
                        if (ProductRevision != null && ProductRevision.ProductRevisionId != value)
                        {
                            ProductRevision = null;
                        }
                    }
                    _productRevisionId = value;
                    OnPropertyChanged("ProductRevisionId");
                }
            }
        }
        private System.Guid _productRevisionId;
    
        [DataMember]
        public Nullable<System.Guid> SiteId
        {
            get { return _siteId; }
            set
            {
                if (_siteId != value)
                {
                    ChangeTracker.RecordOriginalValue("SiteId", _siteId);
                    if (!IsDeserializing)
                    {
                        if (Site != null && Site.SiteId != value)
                        {
                            Site = null;
                        }
                    }
                    _siteId = value;
                    OnPropertyChanged("SiteId");
                }
            }
        }
        private Nullable<System.Guid> _siteId;
    
        [DataMember]
        public Nullable<System.Guid> ProductionBatchId
        {
            get { return _productionBatchId; }
            set
            {
                if (_productionBatchId != value)
                {
                    ChangeTracker.RecordOriginalValue("ProductionBatchId", _productionBatchId);
                    if (!IsDeserializing)
                    {
                        if (ProductionBatch != null && ProductionBatch.ProductionBatchId != value)
                        {
                            ProductionBatch = null;
                        }
                    }
                    _productionBatchId = value;
                    OnPropertyChanged("ProductionBatchId");
                }
            }
        }
        private Nullable<System.Guid> _productionBatchId;
    
        [DataMember]
        public string SerialNumber
        {
            get { return _serialNumber; }
            set
            {
                if (_serialNumber != value)
                {
                    _serialNumber = value;
                    OnPropertyChanged("SerialNumber");
                }
            }
        }
        private string _serialNumber;
    
        [DataMember]
        public Nullable<System.DateTime> SerialDate
        {
            get { return _serialDate; }
            set
            {
                if (_serialDate != value)
                {
                    _serialDate = value;
                    OnPropertyChanged("SerialDate");
                }
            }
        }
        private Nullable<System.DateTime> _serialDate;
    
        [DataMember]
        public string XMLData
        {
            get { return _xMLData; }
            set
            {
                if (_xMLData != value)
                {
                    _xMLData = value;
                    OnPropertyChanged("XMLData");
                }
            }
        }
        private string _xMLData;
    
        [DataMember]
        public string CurrentLocation
        {
            get { return _currentLocation; }
            set
            {
                if (_currentLocation != value)
                {
                    _currentLocation = value;
                    OnPropertyChanged("CurrentLocation");
                }
            }
        }
        private string _currentLocation;
    
        [DataMember]
        public byte[] TStamp
        {
            get { return _tStamp; }
            set
            {
                if (_tStamp != value)
                {
                    _tStamp = value;
                    OnPropertyChanged("TStamp");
                }
            }
        }
        private byte[] _tStamp;
    
        [DataMember]
        public bool Changed
        {
            get { return _changed; }
            set
            {
                if (_changed != value)
                {
                    _changed = value;
                    OnPropertyChanged("Changed");
                }
            }
        }
        private bool _changed;
    
        [DataMember]
        public int UnitPhaseId
        {
            get { return _unitPhaseId; }
            set
            {
                if (_unitPhaseId != value)
                {
                    ChangeTracker.RecordOriginalValue("UnitPhaseId", _unitPhaseId);
                    if (!IsDeserializing)
                    {
                        if (UnitPhase != null && UnitPhase.UnitPhaseId != value)
                        {
                            UnitPhase = null;
                        }
                    }
                    _unitPhaseId = value;
                    OnPropertyChanged("UnitPhaseId");
                }
            }
        }
        private int _unitPhaseId;
    
        [DataMember]
        public System.Guid ProductId
        {
            get { return _productId; }
            set
            {
                if (_productId != value)
                {
                    ChangeTracker.RecordOriginalValue("ProductId", _productId);
                    if (!IsDeserializing)
                    {
                        if (Product != null && Product.ProductId != value)
                        {
                            Product = null;
                        }
                    }
                    _productId = value;
                    OnPropertyChanged("ProductId");
                }
            }
        }
        private System.Guid _productId;
    
        [DataMember]
        public Nullable<System.Guid> ProcessId
        {
            get { return _processId; }
            set
            {
                if (_processId != value)
                {
                    ChangeTracker.RecordOriginalValue("ProcessId", _processId);
                    if (!IsDeserializing)
                    {
                        if (Process != null && Process.ProcessId != value)
                        {
                            Process = null;
                        }
                    }
                    _processId = value;
                    OnPropertyChanged("ProcessId");
                }
            }
        }
        private Nullable<System.Guid> _processId;
    
        [DataMember]
        public Nullable<System.Guid> OrderId
        {
            get { return _orderId; }
            set
            {
                if (_orderId != value)
                {
                    ChangeTracker.RecordOriginalValue("OrderId", _orderId);
                    if (!IsDeserializing)
                    {
                        if (Order != null && Order.OrderId != value)
                        {
                            Order = null;
                        }
                    }
                    _orderId = value;
                    OnPropertyChanged("OrderId");
                }
            }
        }
        private Nullable<System.Guid> _orderId;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Site Site
        {
            get { return _site; }
            set
            {
                if (!ReferenceEquals(_site, value))
                {
                    var previousValue = _site;
                    _site = value;
                    FixupSite(previousValue);
                    OnNavigationPropertyChanged("Site");
                }
            }
        }
        private Site _site;
    
        [DataMember]
        public ProductRevision ProductRevision
        {
            get { return _productRevision; }
            set
            {
                if (!ReferenceEquals(_productRevision, value))
                {
                    var previousValue = _productRevision;
                    _productRevision = value;
                    FixupProductRevision(previousValue);
                    OnNavigationPropertyChanged("ProductRevision");
                }
            }
        }
        private ProductRevision _productRevision;
    
        [DataMember]
        public ProductionBatch ProductionBatch
        {
            get { return _productionBatch; }
            set
            {
                if (!ReferenceEquals(_productionBatch, value))
                {
                    var previousValue = _productionBatch;
                    _productionBatch = value;
                    FixupProductionBatch(previousValue);
                    OnNavigationPropertyChanged("ProductionBatch");
                }
            }
        }
        private ProductionBatch _productionBatch;
    
        [DataMember]
        public TrackableCollection<Unit> Children
        {
            get
            {
                if (_children == null)
                {
                    _children = new TrackableCollection<Unit>();
                    _children.CollectionChanged += FixupChildren;
                }
                return _children;
            }
            set
            {
                if (!ReferenceEquals(_children, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_children != null)
                    {
                        _children.CollectionChanged -= FixupChildren;
                    }
                    _children = value;
                    if (_children != null)
                    {
                        _children.CollectionChanged += FixupChildren;
                    }
                    OnNavigationPropertyChanged("Children");
                }
            }
        }
        private TrackableCollection<Unit> _children;
    
        [DataMember]
        public Unit Parent
        {
            get { return _parent; }
            set
            {
                if (!ReferenceEquals(_parent, value))
                {
                    var previousValue = _parent;
                    _parent = value;
                    FixupParent(previousValue);
                    OnNavigationPropertyChanged("Parent");
                }
            }
        }
        private Unit _parent;
    
        [DataMember]
        public TrackableCollection<WorkflowInstance> WorkflowInstances
        {
            get
            {
                if (_workflowInstances == null)
                {
                    _workflowInstances = new TrackableCollection<WorkflowInstance>();
                    _workflowInstances.CollectionChanged += FixupWorkflowInstances;
                }
                return _workflowInstances;
            }
            set
            {
                if (!ReferenceEquals(_workflowInstances, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_workflowInstances != null)
                    {
                        _workflowInstances.CollectionChanged -= FixupWorkflowInstances;
                    }
                    _workflowInstances = value;
                    if (_workflowInstances != null)
                    {
                        _workflowInstances.CollectionChanged += FixupWorkflowInstances;
                    }
                    OnNavigationPropertyChanged("WorkflowInstances");
                }
            }
        }
        private TrackableCollection<WorkflowInstance> _workflowInstances;
    
        [DataMember]
        public UnitPhase UnitPhase
        {
            get { return _unitPhase; }
            set
            {
                if (!ReferenceEquals(_unitPhase, value))
                {
                    var previousValue = _unitPhase;
                    _unitPhase = value;
                    FixupUnitPhase(previousValue);
                    OnNavigationPropertyChanged("UnitPhase");
                }
            }
        }
        private UnitPhase _unitPhase;
    
        [DataMember]
        public Product Product
        {
            get { return _product; }
            set
            {
                if (!ReferenceEquals(_product, value))
                {
                    var previousValue = _product;
                    _product = value;
                    FixupProduct(previousValue);
                    OnNavigationPropertyChanged("Product");
                }
            }
        }
        private Product _product;
    
        [DataMember]
        public Process Process
        {
            get { return _process; }
            set
            {
                if (!ReferenceEquals(_process, value))
                {
                    var previousValue = _process;
                    _process = value;
                    FixupProcess(previousValue);
                    OnNavigationPropertyChanged("Process");
                }
            }
        }
        private Process _process;
    
        [DataMember]
        public Order Order
        {
            get { return _order; }
            set
            {
                if (!ReferenceEquals(_order, value))
                {
                    var previousValue = _order;
                    _order = value;
                    FixupOrder(previousValue);
                    OnNavigationPropertyChanged("Order");
                }
            }
        }
        private Order _order;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Site = null;
            ProductRevision = null;
            ProductionBatch = null;
            Children.Clear();
            Parent = null;
            WorkflowInstances.Clear();
            UnitPhase = null;
            Product = null;
            Process = null;
            Order = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupSite(Site previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Units.Contains(this))
            {
                previousValue.Units.Remove(this);
            }
    
            if (Site != null)
            {
                if (!Site.Units.Contains(this))
                {
                    Site.Units.Add(this);
                }
    
                SiteId = Site.SiteId;
            }
            else if (!skipKeys)
            {
                SiteId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Site")
                    && (ChangeTracker.OriginalValues["Site"] == Site))
                {
                    ChangeTracker.OriginalValues.Remove("Site");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Site", previousValue);
                }
                if (Site != null && !Site.ChangeTracker.ChangeTrackingEnabled)
                {
                    Site.StartTracking();
                }
            }
        }
    
        private void FixupProductRevision(ProductRevision previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Units.Contains(this))
            {
                previousValue.Units.Remove(this);
            }
    
            if (ProductRevision != null)
            {
                if (!ProductRevision.Units.Contains(this))
                {
                    ProductRevision.Units.Add(this);
                }
    
                ProductRevisionId = ProductRevision.ProductRevisionId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ProductRevision")
                    && (ChangeTracker.OriginalValues["ProductRevision"] == ProductRevision))
                {
                    ChangeTracker.OriginalValues.Remove("ProductRevision");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ProductRevision", previousValue);
                }
                if (ProductRevision != null && !ProductRevision.ChangeTracker.ChangeTrackingEnabled)
                {
                    ProductRevision.StartTracking();
                }
            }
        }
    
        private void FixupProductionBatch(ProductionBatch previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Units.Contains(this))
            {
                previousValue.Units.Remove(this);
            }
    
            if (ProductionBatch != null)
            {
                if (!ProductionBatch.Units.Contains(this))
                {
                    ProductionBatch.Units.Add(this);
                }
    
                ProductionBatchId = ProductionBatch.ProductionBatchId;
            }
            else if (!skipKeys)
            {
                ProductionBatchId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ProductionBatch")
                    && (ChangeTracker.OriginalValues["ProductionBatch"] == ProductionBatch))
                {
                    ChangeTracker.OriginalValues.Remove("ProductionBatch");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ProductionBatch", previousValue);
                }
                if (ProductionBatch != null && !ProductionBatch.ChangeTracker.ChangeTrackingEnabled)
                {
                    ProductionBatch.StartTracking();
                }
            }
        }
    
        private void FixupParent(Unit previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Children.Contains(this))
            {
                previousValue.Children.Remove(this);
            }
    
            if (Parent != null)
            {
                if (!Parent.Children.Contains(this))
                {
                    Parent.Children.Add(this);
                }
    
                ParentUnitId = Parent.UnitId;
            }
            else if (!skipKeys)
            {
                ParentUnitId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Parent")
                    && (ChangeTracker.OriginalValues["Parent"] == Parent))
                {
                    ChangeTracker.OriginalValues.Remove("Parent");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Parent", previousValue);
                }
                if (Parent != null && !Parent.ChangeTracker.ChangeTrackingEnabled)
                {
                    Parent.StartTracking();
                }
            }
        }
    
        private void FixupUnitPhase(UnitPhase previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Units.Contains(this))
            {
                previousValue.Units.Remove(this);
            }
    
            if (UnitPhase != null)
            {
                if (!UnitPhase.Units.Contains(this))
                {
                    UnitPhase.Units.Add(this);
                }
    
                UnitPhaseId = UnitPhase.UnitPhaseId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("UnitPhase")
                    && (ChangeTracker.OriginalValues["UnitPhase"] == UnitPhase))
                {
                    ChangeTracker.OriginalValues.Remove("UnitPhase");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("UnitPhase", previousValue);
                }
                if (UnitPhase != null && !UnitPhase.ChangeTracker.ChangeTrackingEnabled)
                {
                    UnitPhase.StartTracking();
                }
            }
        }
    
        private void FixupProduct(Product previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Units.Contains(this))
            {
                previousValue.Units.Remove(this);
            }
    
            if (Product != null)
            {
                if (!Product.Units.Contains(this))
                {
                    Product.Units.Add(this);
                }
    
                ProductId = Product.ProductId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Product")
                    && (ChangeTracker.OriginalValues["Product"] == Product))
                {
                    ChangeTracker.OriginalValues.Remove("Product");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Product", previousValue);
                }
                if (Product != null && !Product.ChangeTracker.ChangeTrackingEnabled)
                {
                    Product.StartTracking();
                }
            }
        }
    
        private void FixupProcess(Process previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Units.Contains(this))
            {
                previousValue.Units.Remove(this);
            }
    
            if (Process != null)
            {
                if (!Process.Units.Contains(this))
                {
                    Process.Units.Add(this);
                }
    
                ProcessId = Process.ProcessId;
            }
            else if (!skipKeys)
            {
                ProcessId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Process")
                    && (ChangeTracker.OriginalValues["Process"] == Process))
                {
                    ChangeTracker.OriginalValues.Remove("Process");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Process", previousValue);
                }
                if (Process != null && !Process.ChangeTracker.ChangeTrackingEnabled)
                {
                    Process.StartTracking();
                }
            }
        }
    
        private void FixupOrder(Order previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Units.Contains(this))
            {
                previousValue.Units.Remove(this);
            }
    
            if (Order != null)
            {
                if (!Order.Units.Contains(this))
                {
                    Order.Units.Add(this);
                }
    
                OrderId = Order.OrderId;
            }
            else if (!skipKeys)
            {
                OrderId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Order")
                    && (ChangeTracker.OriginalValues["Order"] == Order))
                {
                    ChangeTracker.OriginalValues.Remove("Order");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Order", previousValue);
                }
                if (Order != null && !Order.ChangeTracker.ChangeTrackingEnabled)
                {
                    Order.StartTracking();
                }
            }
        }
    
        private void FixupChildren(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Unit item in e.NewItems)
                {
                    item.Parent = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Children", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Unit item in e.OldItems)
                {
                    if (ReferenceEquals(item.Parent, this))
                    {
                        item.Parent = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Children", item);
                    }
                }
            }
        }
    
        private void FixupWorkflowInstances(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (WorkflowInstance item in e.NewItems)
                {
                    item.Unit = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("WorkflowInstances", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (WorkflowInstance item in e.OldItems)
                {
                    if (ReferenceEquals(item.Unit, this))
                    {
                        item.Unit = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("WorkflowInstances", item);
                    }
                }
            }
        }

        #endregion

    }
}
