//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(VirtualFolder))]
    [KnownType(typeof(WorkflowDefinition))]
    [KnownType(typeof(Package))]
    [KnownType(typeof(TestSequenceDefinition))]
    public partial class VirtualFolder: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid VirtualFolderId
        {
            get { return _virtualFolderId; }
            set
            {
                if (_virtualFolderId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'VirtualFolderId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _virtualFolderId = value;
                    OnPropertyChanged("VirtualFolderId");
                }
            }
        }
        private System.Guid _virtualFolderId;
    
        [DataMember]
        public Nullable<System.Guid> ParentVirtualFolderId
        {
            get { return _parentVirtualFolderId; }
            set
            {
                if (_parentVirtualFolderId != value)
                {
                    ChangeTracker.RecordOriginalValue("ParentVirtualFolderId", _parentVirtualFolderId);
                    if (!IsDeserializing)
                    {
                        if (Parent != null && Parent.VirtualFolderId != value)
                        {
                            Parent = null;
                        }
                    }
                    _parentVirtualFolderId = value;
                    OnPropertyChanged("ParentVirtualFolderId");
                }
            }
        }
        private Nullable<System.Guid> _parentVirtualFolderId;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;
    
        [DataMember]
        public int Type
        {
            get { return _type; }
            set
            {
                if (_type != value)
                {
                    _type = value;
                    OnPropertyChanged("Type");
                }
            }
        }
        private int _type;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<VirtualFolder> Children
        {
            get
            {
                if (_children == null)
                {
                    _children = new TrackableCollection<VirtualFolder>();
                    _children.CollectionChanged += FixupChildren;
                }
                return _children;
            }
            set
            {
                if (!ReferenceEquals(_children, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_children != null)
                    {
                        _children.CollectionChanged -= FixupChildren;
                    }
                    _children = value;
                    if (_children != null)
                    {
                        _children.CollectionChanged += FixupChildren;
                    }
                    OnNavigationPropertyChanged("Children");
                }
            }
        }
        private TrackableCollection<VirtualFolder> _children;
    
        [DataMember]
        public VirtualFolder Parent
        {
            get { return _parent; }
            set
            {
                if (!ReferenceEquals(_parent, value))
                {
                    var previousValue = _parent;
                    _parent = value;
                    FixupParent(previousValue);
                    OnNavigationPropertyChanged("Parent");
                }
            }
        }
        private VirtualFolder _parent;
    
        [DataMember]
        public TrackableCollection<WorkflowDefinition> WorkflowDefinitions
        {
            get
            {
                if (_workflowDefinitions == null)
                {
                    _workflowDefinitions = new TrackableCollection<WorkflowDefinition>();
                    _workflowDefinitions.CollectionChanged += FixupWorkflowDefinitions;
                }
                return _workflowDefinitions;
            }
            set
            {
                if (!ReferenceEquals(_workflowDefinitions, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_workflowDefinitions != null)
                    {
                        _workflowDefinitions.CollectionChanged -= FixupWorkflowDefinitions;
                    }
                    _workflowDefinitions = value;
                    if (_workflowDefinitions != null)
                    {
                        _workflowDefinitions.CollectionChanged += FixupWorkflowDefinitions;
                    }
                    OnNavigationPropertyChanged("WorkflowDefinitions");
                }
            }
        }
        private TrackableCollection<WorkflowDefinition> _workflowDefinitions;
    
        [DataMember]
        public TrackableCollection<Package> Packages
        {
            get
            {
                if (_packages == null)
                {
                    _packages = new TrackableCollection<Package>();
                    _packages.CollectionChanged += FixupPackages;
                }
                return _packages;
            }
            set
            {
                if (!ReferenceEquals(_packages, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_packages != null)
                    {
                        _packages.CollectionChanged -= FixupPackages;
                    }
                    _packages = value;
                    if (_packages != null)
                    {
                        _packages.CollectionChanged += FixupPackages;
                    }
                    OnNavigationPropertyChanged("Packages");
                }
            }
        }
        private TrackableCollection<Package> _packages;
    
        [DataMember]
        public TrackableCollection<TestSequenceDefinition> TestSequenceDefinitions
        {
            get
            {
                if (_testSequenceDefinitions == null)
                {
                    _testSequenceDefinitions = new TrackableCollection<TestSequenceDefinition>();
                    _testSequenceDefinitions.CollectionChanged += FixupTestSequenceDefinitions;
                }
                return _testSequenceDefinitions;
            }
            set
            {
                if (!ReferenceEquals(_testSequenceDefinitions, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_testSequenceDefinitions != null)
                    {
                        _testSequenceDefinitions.CollectionChanged -= FixupTestSequenceDefinitions;
                    }
                    _testSequenceDefinitions = value;
                    if (_testSequenceDefinitions != null)
                    {
                        _testSequenceDefinitions.CollectionChanged += FixupTestSequenceDefinitions;
                    }
                    OnNavigationPropertyChanged("TestSequenceDefinitions");
                }
            }
        }
        private TrackableCollection<TestSequenceDefinition> _testSequenceDefinitions;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Children.Clear();
            Parent = null;
            WorkflowDefinitions.Clear();
            Packages.Clear();
            TestSequenceDefinitions.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupParent(VirtualFolder previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Children.Contains(this))
            {
                previousValue.Children.Remove(this);
            }
    
            if (Parent != null)
            {
                if (!Parent.Children.Contains(this))
                {
                    Parent.Children.Add(this);
                }
    
                ParentVirtualFolderId = Parent.VirtualFolderId;
            }
            else if (!skipKeys)
            {
                ParentVirtualFolderId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Parent")
                    && (ChangeTracker.OriginalValues["Parent"] == Parent))
                {
                    ChangeTracker.OriginalValues.Remove("Parent");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Parent", previousValue);
                }
                if (Parent != null && !Parent.ChangeTracker.ChangeTrackingEnabled)
                {
                    Parent.StartTracking();
                }
            }
        }
    
        private void FixupChildren(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (VirtualFolder item in e.NewItems)
                {
                    item.Parent = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Children", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (VirtualFolder item in e.OldItems)
                {
                    if (ReferenceEquals(item.Parent, this))
                    {
                        item.Parent = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Children", item);
                    }
                }
            }
        }
    
        private void FixupWorkflowDefinitions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (WorkflowDefinition item in e.NewItems)
                {
                    item.VirtualFolder = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("WorkflowDefinitions", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (WorkflowDefinition item in e.OldItems)
                {
                    if (ReferenceEquals(item.VirtualFolder, this))
                    {
                        item.VirtualFolder = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("WorkflowDefinitions", item);
                    }
                }
            }
        }
    
        private void FixupPackages(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Package item in e.NewItems)
                {
                    item.VirtualFolder = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Packages", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Package item in e.OldItems)
                {
                    if (ReferenceEquals(item.VirtualFolder, this))
                    {
                        item.VirtualFolder = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Packages", item);
                    }
                }
            }
        }
    
        private void FixupTestSequenceDefinitions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TestSequenceDefinition item in e.NewItems)
                {
                    item.VirtualFolder = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TestSequenceDefinitions", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TestSequenceDefinition item in e.OldItems)
                {
                    if (ReferenceEquals(item.VirtualFolder, this))
                    {
                        item.VirtualFolder = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TestSequenceDefinitions", item);
                    }
                }
            }
        }

        #endregion

    }
}
