//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(WorkflowInstance))]
    [KnownType(typeof(WorkflowDefinition))]
    [KnownType(typeof(WorkflowRelationSiteRelation))]
    public partial class WorkflowRelation: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid WorkflowRelationId
        {
            get { return _workflowRelationId; }
            set
            {
                if (_workflowRelationId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'WorkflowRelationId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _workflowRelationId = value;
                    OnPropertyChanged("WorkflowRelationId");
                }
            }
        }
        private System.Guid _workflowRelationId;
    
        [DataMember]
        public System.Guid WorkflowDefinitionId
        {
            get { return _workflowDefinitionId; }
            set
            {
                if (_workflowDefinitionId != value)
                {
                    ChangeTracker.RecordOriginalValue("WorkflowDefinitionId", _workflowDefinitionId);
                    if (!IsDeserializing)
                    {
                        if (WorkflowDefinition != null && WorkflowDefinition.WorkflowDefinitionId != value)
                        {
                            WorkflowDefinition = null;
                        }
                    }
                    _workflowDefinitionId = value;
                    OnPropertyChanged("WorkflowDefinitionId");
                }
            }
        }
        private System.Guid _workflowDefinitionId;
    
        [DataMember]
        public string EntitySchema
        {
            get { return _entitySchema; }
            set
            {
                if (_entitySchema != value)
                {
                    _entitySchema = value;
                    OnPropertyChanged("EntitySchema");
                }
            }
        }
        private string _entitySchema;
    
        [DataMember]
        public string EntityName
        {
            get { return _entityName; }
            set
            {
                if (_entityName != value)
                {
                    _entityName = value;
                    OnPropertyChanged("EntityName");
                }
            }
        }
        private string _entityName;
    
        [DataMember]
        public string EntityKeyName
        {
            get { return _entityKeyName; }
            set
            {
                if (_entityKeyName != value)
                {
                    _entityKeyName = value;
                    OnPropertyChanged("EntityKeyName");
                }
            }
        }
        private string _entityKeyName;
    
        [DataMember]
        public int Status
        {
            get { return _status; }
            set
            {
                if (_status != value)
                {
                    _status = value;
                    OnPropertyChanged("Status");
                }
            }
        }
        private int _status;
    
        [DataMember]
        public string EntityValue
        {
            get { return _entityValue; }
            set
            {
                if (_entityValue != value)
                {
                    _entityValue = value;
                    OnPropertyChanged("EntityValue");
                }
            }
        }
        private string _entityValue;
    
        [DataMember]
        public string Parameters
        {
            get { return _parameters; }
            set
            {
                if (_parameters != value)
                {
                    _parameters = value;
                    OnPropertyChanged("Parameters");
                }
            }
        }
        private string _parameters;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<WorkflowInstance> WorkflowInstances
        {
            get
            {
                if (_workflowInstances == null)
                {
                    _workflowInstances = new TrackableCollection<WorkflowInstance>();
                    _workflowInstances.CollectionChanged += FixupWorkflowInstances;
                }
                return _workflowInstances;
            }
            set
            {
                if (!ReferenceEquals(_workflowInstances, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_workflowInstances != null)
                    {
                        _workflowInstances.CollectionChanged -= FixupWorkflowInstances;
                    }
                    _workflowInstances = value;
                    if (_workflowInstances != null)
                    {
                        _workflowInstances.CollectionChanged += FixupWorkflowInstances;
                    }
                    OnNavigationPropertyChanged("WorkflowInstances");
                }
            }
        }
        private TrackableCollection<WorkflowInstance> _workflowInstances;
    
        [DataMember]
        public WorkflowDefinition WorkflowDefinition
        {
            get { return _workflowDefinition; }
            set
            {
                if (!ReferenceEquals(_workflowDefinition, value))
                {
                    var previousValue = _workflowDefinition;
                    _workflowDefinition = value;
                    FixupWorkflowDefinition(previousValue);
                    OnNavigationPropertyChanged("WorkflowDefinition");
                }
            }
        }
        private WorkflowDefinition _workflowDefinition;
    
        [DataMember]
        public TrackableCollection<WorkflowRelationSiteRelation> WorkflowRelationSiteRelations
        {
            get
            {
                if (_workflowRelationSiteRelations == null)
                {
                    _workflowRelationSiteRelations = new TrackableCollection<WorkflowRelationSiteRelation>();
                    _workflowRelationSiteRelations.CollectionChanged += FixupWorkflowRelationSiteRelations;
                }
                return _workflowRelationSiteRelations;
            }
            set
            {
                if (!ReferenceEquals(_workflowRelationSiteRelations, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_workflowRelationSiteRelations != null)
                    {
                        _workflowRelationSiteRelations.CollectionChanged -= FixupWorkflowRelationSiteRelations;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (WorkflowRelationSiteRelation item in _workflowRelationSiteRelations)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _workflowRelationSiteRelations = value;
                    if (_workflowRelationSiteRelations != null)
                    {
                        _workflowRelationSiteRelations.CollectionChanged += FixupWorkflowRelationSiteRelations;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (WorkflowRelationSiteRelation item in _workflowRelationSiteRelations)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("WorkflowRelationSiteRelations");
                }
            }
        }
        private TrackableCollection<WorkflowRelationSiteRelation> _workflowRelationSiteRelations;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            WorkflowInstances.Clear();
            WorkflowDefinition = null;
            WorkflowRelationSiteRelations.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupWorkflowDefinition(WorkflowDefinition previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowRelations.Contains(this))
            {
                previousValue.WorkflowRelations.Remove(this);
            }
    
            if (WorkflowDefinition != null)
            {
                if (!WorkflowDefinition.WorkflowRelations.Contains(this))
                {
                    WorkflowDefinition.WorkflowRelations.Add(this);
                }
    
                WorkflowDefinitionId = WorkflowDefinition.WorkflowDefinitionId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("WorkflowDefinition")
                    && (ChangeTracker.OriginalValues["WorkflowDefinition"] == WorkflowDefinition))
                {
                    ChangeTracker.OriginalValues.Remove("WorkflowDefinition");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("WorkflowDefinition", previousValue);
                }
                if (WorkflowDefinition != null && !WorkflowDefinition.ChangeTracker.ChangeTrackingEnabled)
                {
                    WorkflowDefinition.StartTracking();
                }
            }
        }
    
        private void FixupWorkflowInstances(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (WorkflowInstance item in e.NewItems)
                {
                    item.WorkflowRelation = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("WorkflowInstances", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (WorkflowInstance item in e.OldItems)
                {
                    if (ReferenceEquals(item.WorkflowRelation, this))
                    {
                        item.WorkflowRelation = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("WorkflowInstances", item);
                    }
                }
            }
        }
    
        private void FixupWorkflowRelationSiteRelations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (WorkflowRelationSiteRelation item in e.NewItems)
                {
                    item.WorkflowRelation = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("WorkflowRelationSiteRelations", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (WorkflowRelationSiteRelation item in e.OldItems)
                {
                    if (ReferenceEquals(item.WorkflowRelation, this))
                    {
                        item.WorkflowRelation = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("WorkflowRelationSiteRelations", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion

    }
}
