//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(WorkflowActivity))]
    public partial class WorkflowActivityLog: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int WorkflowActivityLogId
        {
            get { return _workflowActivityLogId; }
            set
            {
                if (_workflowActivityLogId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'WorkflowActivityLogId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _workflowActivityLogId = value;
                    OnPropertyChanged("WorkflowActivityLogId");
                }
            }
        }
        private int _workflowActivityLogId;
    
        [DataMember]
        public System.Guid WorkflowId
        {
            get { return _workflowId; }
            set
            {
                if (_workflowId != value)
                {
                    _workflowId = value;
                    OnPropertyChanged("WorkflowId");
                }
            }
        }
        private System.Guid _workflowId;
    
        [DataMember]
        public Nullable<System.Guid> WorkflowActivityId
        {
            get { return _workflowActivityId; }
            set
            {
                if (_workflowActivityId != value)
                {
                    ChangeTracker.RecordOriginalValue("WorkflowActivityId", _workflowActivityId);
                    if (!IsDeserializing)
                    {
                        if (WorkflowActivity != null && WorkflowActivity.WorkflowActivityId != value)
                        {
                            WorkflowActivity = null;
                        }
                    }
                    _workflowActivityId = value;
                    OnPropertyChanged("WorkflowActivityId");
                }
            }
        }
        private Nullable<System.Guid> _workflowActivityId;
    
        [DataMember]
        public string ActivityType
        {
            get { return _activityType; }
            set
            {
                if (_activityType != value)
                {
                    _activityType = value;
                    OnPropertyChanged("ActivityType");
                }
            }
        }
        private string _activityType;
    
        [DataMember]
        public string ProcessCode
        {
            get { return _processCode; }
            set
            {
                if (_processCode != value)
                {
                    _processCode = value;
                    OnPropertyChanged("ProcessCode");
                }
            }
        }
        private string _processCode;
    
        [DataMember]
        public System.DateTime Start
        {
            get { return _start; }
            set
            {
                if (_start != value)
                {
                    _start = value;
                    OnPropertyChanged("Start");
                }
            }
        }
        private System.DateTime _start;
    
        [DataMember]
        public Nullable<System.DateTime> End
        {
            get { return _end; }
            set
            {
                if (_end != value)
                {
                    _end = value;
                    OnPropertyChanged("End");
                }
            }
        }
        private Nullable<System.DateTime> _end;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public WorkflowActivity WorkflowActivity
        {
            get { return _workflowActivity; }
            set
            {
                if (!ReferenceEquals(_workflowActivity, value))
                {
                    var previousValue = _workflowActivity;
                    _workflowActivity = value;
                    FixupWorkflowActivity(previousValue);
                    OnNavigationPropertyChanged("WorkflowActivity");
                }
            }
        }
        private WorkflowActivity _workflowActivity;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            WorkflowActivity = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupWorkflowActivity(WorkflowActivity previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowActivityLogs.Contains(this))
            {
                previousValue.WorkflowActivityLogs.Remove(this);
            }
    
            if (WorkflowActivity != null)
            {
                if (!WorkflowActivity.WorkflowActivityLogs.Contains(this))
                {
                    WorkflowActivity.WorkflowActivityLogs.Add(this);
                }
    
                WorkflowActivityId = WorkflowActivity.WorkflowActivityId;
            }
            else if (!skipKeys)
            {
                WorkflowActivityId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("WorkflowActivity")
                    && (ChangeTracker.OriginalValues["WorkflowActivity"] == WorkflowActivity))
                {
                    ChangeTracker.OriginalValues.Remove("WorkflowActivity");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("WorkflowActivity", previousValue);
                }
                if (WorkflowActivity != null && !WorkflowActivity.ChangeTracker.ChangeTrackingEnabled)
                {
                    WorkflowActivity.StartTracking();
                }
            }
        }

        #endregion

    }
}
