//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Unit))]
    [KnownType(typeof(WorkflowInstance))]
    [KnownType(typeof(WorkflowRelation))]
    [KnownType(typeof(WorkflowDefinition))]
    [KnownType(typeof(WorkflowActivity))]
    public partial class WorkflowInstance: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid WorkflowId
        {
            get { return _workflowId; }
            set
            {
                if (_workflowId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'WorkflowId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _workflowId = value;
                    OnPropertyChanged("WorkflowId");
                }
            }
        }
        private System.Guid _workflowId;
    
        [DataMember]
        public Nullable<System.Guid> ParentWorkflowId
        {
            get { return _parentWorkflowId; }
            set
            {
                if (_parentWorkflowId != value)
                {
                    ChangeTracker.RecordOriginalValue("ParentWorkflowId", _parentWorkflowId);
                    if (!IsDeserializing)
                    {
                        if (Parent != null && Parent.WorkflowId != value)
                        {
                            Parent = null;
                        }
                    }
                    _parentWorkflowId = value;
                    OnPropertyChanged("ParentWorkflowId");
                }
            }
        }
        private Nullable<System.Guid> _parentWorkflowId;
    
        [DataMember]
        public System.Guid WorkflowDefinitionId
        {
            get { return _workflowDefinitionId; }
            set
            {
                if (_workflowDefinitionId != value)
                {
                    ChangeTracker.RecordOriginalValue("WorkflowDefinitionId", _workflowDefinitionId);
                    if (!IsDeserializing)
                    {
                        if (WorkflowDefinition != null && WorkflowDefinition.WorkflowDefinitionId != value)
                        {
                            WorkflowDefinition = null;
                        }
                    }
                    _workflowDefinitionId = value;
                    OnPropertyChanged("WorkflowDefinitionId");
                }
            }
        }
        private System.Guid _workflowDefinitionId;
    
        [DataMember]
        public Nullable<System.Guid> WorkflowRelationId
        {
            get { return _workflowRelationId; }
            set
            {
                if (_workflowRelationId != value)
                {
                    ChangeTracker.RecordOriginalValue("WorkflowRelationId", _workflowRelationId);
                    if (!IsDeserializing)
                    {
                        if (WorkflowRelation != null && WorkflowRelation.WorkflowRelationId != value)
                        {
                            WorkflowRelation = null;
                        }
                    }
                    _workflowRelationId = value;
                    OnPropertyChanged("WorkflowRelationId");
                }
            }
        }
        private Nullable<System.Guid> _workflowRelationId;
    
        [DataMember]
        public System.Guid UnitId
        {
            get { return _unitId; }
            set
            {
                if (_unitId != value)
                {
                    ChangeTracker.RecordOriginalValue("UnitId", _unitId);
                    if (!IsDeserializing)
                    {
                        if (Unit != null && Unit.UnitId != value)
                        {
                            Unit = null;
                        }
                    }
                    _unitId = value;
                    OnPropertyChanged("UnitId");
                }
            }
        }
        private System.Guid _unitId;
    
        [DataMember]
        public int State
        {
            get { return _state; }
            set
            {
                if (_state != value)
                {
                    _state = value;
                    OnPropertyChanged("State");
                }
            }
        }
        private int _state;
    
        [DataMember]
        public Nullable<System.Guid> NativeWorkflowInstanceId
        {
            get { return _nativeWorkflowInstanceId; }
            set
            {
                if (_nativeWorkflowInstanceId != value)
                {
                    _nativeWorkflowInstanceId = value;
                    OnPropertyChanged("NativeWorkflowInstanceId");
                }
            }
        }
        private Nullable<System.Guid> _nativeWorkflowInstanceId;
    
        [DataMember]
        public Nullable<System.Guid> LastWorkflowActivityId
        {
            get { return _lastWorkflowActivityId; }
            set
            {
                if (_lastWorkflowActivityId != value)
                {
                    ChangeTracker.RecordOriginalValue("LastWorkflowActivityId", _lastWorkflowActivityId);
                    if (!IsDeserializing)
                    {
                        if (WorkflowActivity != null && WorkflowActivity.WorkflowActivityId != value)
                        {
                            WorkflowActivity = null;
                        }
                    }
                    _lastWorkflowActivityId = value;
                    OnPropertyChanged("LastWorkflowActivityId");
                }
            }
        }
        private Nullable<System.Guid> _lastWorkflowActivityId;
    
        [DataMember]
        public Nullable<int> LastActivityLogId
        {
            get { return _lastActivityLogId; }
            set
            {
                if (_lastActivityLogId != value)
                {
                    _lastActivityLogId = value;
                    OnPropertyChanged("LastActivityLogId");
                }
            }
        }
        private Nullable<int> _lastActivityLogId;
    
        [DataMember]
        public Nullable<System.DateTime> LastEventTime
        {
            get { return _lastEventTime; }
            set
            {
                if (_lastEventTime != value)
                {
                    _lastEventTime = value;
                    OnPropertyChanged("LastEventTime");
                }
            }
        }
        private Nullable<System.DateTime> _lastEventTime;
    
        [DataMember]
        public Nullable<int> CurrentActivityLogId
        {
            get { return _currentActivityLogId; }
            set
            {
                if (_currentActivityLogId != value)
                {
                    _currentActivityLogId = value;
                    OnPropertyChanged("CurrentActivityLogId");
                }
            }
        }
        private Nullable<int> _currentActivityLogId;
    
        [DataMember]
        public Nullable<int> WorkflowServiceVersion
        {
            get { return _workflowServiceVersion; }
            set
            {
                if (_workflowServiceVersion != value)
                {
                    _workflowServiceVersion = value;
                    OnPropertyChanged("WorkflowServiceVersion");
                }
            }
        }
        private Nullable<int> _workflowServiceVersion;
    
        [DataMember]
        public Nullable<System.Guid> SiteId
        {
            get { return _siteId; }
            set
            {
                if (_siteId != value)
                {
                    _siteId = value;
                    OnPropertyChanged("SiteId");
                }
            }
        }
        private Nullable<System.Guid> _siteId;
    
        [DataMember]
        public System.DateTime Created
        {
            get { return _created; }
            set
            {
                if (_created != value)
                {
                    _created = value;
                    OnPropertyChanged("Created");
                }
            }
        }
        private System.DateTime _created;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Unit Unit
        {
            get { return _unit; }
            set
            {
                if (!ReferenceEquals(_unit, value))
                {
                    var previousValue = _unit;
                    _unit = value;
                    FixupUnit(previousValue);
                    OnNavigationPropertyChanged("Unit");
                }
            }
        }
        private Unit _unit;
    
        [DataMember]
        public TrackableCollection<WorkflowInstance> Children
        {
            get
            {
                if (_children == null)
                {
                    _children = new TrackableCollection<WorkflowInstance>();
                    _children.CollectionChanged += FixupChildren;
                }
                return _children;
            }
            set
            {
                if (!ReferenceEquals(_children, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_children != null)
                    {
                        _children.CollectionChanged -= FixupChildren;
                    }
                    _children = value;
                    if (_children != null)
                    {
                        _children.CollectionChanged += FixupChildren;
                    }
                    OnNavigationPropertyChanged("Children");
                }
            }
        }
        private TrackableCollection<WorkflowInstance> _children;
    
        [DataMember]
        public WorkflowInstance Parent
        {
            get { return _parent; }
            set
            {
                if (!ReferenceEquals(_parent, value))
                {
                    var previousValue = _parent;
                    _parent = value;
                    FixupParent(previousValue);
                    OnNavigationPropertyChanged("Parent");
                }
            }
        }
        private WorkflowInstance _parent;
    
        [DataMember]
        public WorkflowRelation WorkflowRelation
        {
            get { return _workflowRelation; }
            set
            {
                if (!ReferenceEquals(_workflowRelation, value))
                {
                    var previousValue = _workflowRelation;
                    _workflowRelation = value;
                    FixupWorkflowRelation(previousValue);
                    OnNavigationPropertyChanged("WorkflowRelation");
                }
            }
        }
        private WorkflowRelation _workflowRelation;
    
        [DataMember]
        public WorkflowDefinition WorkflowDefinition
        {
            get { return _workflowDefinition; }
            set
            {
                if (!ReferenceEquals(_workflowDefinition, value))
                {
                    var previousValue = _workflowDefinition;
                    _workflowDefinition = value;
                    FixupWorkflowDefinition(previousValue);
                    OnNavigationPropertyChanged("WorkflowDefinition");
                }
            }
        }
        private WorkflowDefinition _workflowDefinition;
    
        [DataMember]
        public WorkflowActivity WorkflowActivity
        {
            get { return _workflowActivity; }
            set
            {
                if (!ReferenceEquals(_workflowActivity, value))
                {
                    var previousValue = _workflowActivity;
                    _workflowActivity = value;
                    FixupWorkflowActivity(previousValue);
                    OnNavigationPropertyChanged("WorkflowActivity");
                }
            }
        }
        private WorkflowActivity _workflowActivity;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Unit = null;
            Children.Clear();
            Parent = null;
            WorkflowRelation = null;
            WorkflowDefinition = null;
            WorkflowActivity = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupUnit(Unit previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowInstances.Contains(this))
            {
                previousValue.WorkflowInstances.Remove(this);
            }
    
            if (Unit != null)
            {
                if (!Unit.WorkflowInstances.Contains(this))
                {
                    Unit.WorkflowInstances.Add(this);
                }
    
                UnitId = Unit.UnitId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Unit")
                    && (ChangeTracker.OriginalValues["Unit"] == Unit))
                {
                    ChangeTracker.OriginalValues.Remove("Unit");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Unit", previousValue);
                }
                if (Unit != null && !Unit.ChangeTracker.ChangeTrackingEnabled)
                {
                    Unit.StartTracking();
                }
            }
        }
    
        private void FixupParent(WorkflowInstance previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Children.Contains(this))
            {
                previousValue.Children.Remove(this);
            }
    
            if (Parent != null)
            {
                if (!Parent.Children.Contains(this))
                {
                    Parent.Children.Add(this);
                }
    
                ParentWorkflowId = Parent.WorkflowId;
            }
            else if (!skipKeys)
            {
                ParentWorkflowId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Parent")
                    && (ChangeTracker.OriginalValues["Parent"] == Parent))
                {
                    ChangeTracker.OriginalValues.Remove("Parent");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Parent", previousValue);
                }
                if (Parent != null && !Parent.ChangeTracker.ChangeTrackingEnabled)
                {
                    Parent.StartTracking();
                }
            }
        }
    
        private void FixupWorkflowRelation(WorkflowRelation previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowInstances.Contains(this))
            {
                previousValue.WorkflowInstances.Remove(this);
            }
    
            if (WorkflowRelation != null)
            {
                if (!WorkflowRelation.WorkflowInstances.Contains(this))
                {
                    WorkflowRelation.WorkflowInstances.Add(this);
                }
    
                WorkflowRelationId = WorkflowRelation.WorkflowRelationId;
            }
            else if (!skipKeys)
            {
                WorkflowRelationId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("WorkflowRelation")
                    && (ChangeTracker.OriginalValues["WorkflowRelation"] == WorkflowRelation))
                {
                    ChangeTracker.OriginalValues.Remove("WorkflowRelation");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("WorkflowRelation", previousValue);
                }
                if (WorkflowRelation != null && !WorkflowRelation.ChangeTracker.ChangeTrackingEnabled)
                {
                    WorkflowRelation.StartTracking();
                }
            }
        }
    
        private void FixupWorkflowDefinition(WorkflowDefinition previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowInstances.Contains(this))
            {
                previousValue.WorkflowInstances.Remove(this);
            }
    
            if (WorkflowDefinition != null)
            {
                if (!WorkflowDefinition.WorkflowInstances.Contains(this))
                {
                    WorkflowDefinition.WorkflowInstances.Add(this);
                }
    
                WorkflowDefinitionId = WorkflowDefinition.WorkflowDefinitionId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("WorkflowDefinition")
                    && (ChangeTracker.OriginalValues["WorkflowDefinition"] == WorkflowDefinition))
                {
                    ChangeTracker.OriginalValues.Remove("WorkflowDefinition");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("WorkflowDefinition", previousValue);
                }
                if (WorkflowDefinition != null && !WorkflowDefinition.ChangeTracker.ChangeTrackingEnabled)
                {
                    WorkflowDefinition.StartTracking();
                }
            }
        }
    
        private void FixupWorkflowActivity(WorkflowActivity previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.WorkflowInstances.Contains(this))
            {
                previousValue.WorkflowInstances.Remove(this);
            }
    
            if (WorkflowActivity != null)
            {
                if (!WorkflowActivity.WorkflowInstances.Contains(this))
                {
                    WorkflowActivity.WorkflowInstances.Add(this);
                }
    
                LastWorkflowActivityId = WorkflowActivity.WorkflowActivityId;
            }
            else if (!skipKeys)
            {
                LastWorkflowActivityId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("WorkflowActivity")
                    && (ChangeTracker.OriginalValues["WorkflowActivity"] == WorkflowActivity))
                {
                    ChangeTracker.OriginalValues.Remove("WorkflowActivity");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("WorkflowActivity", previousValue);
                }
                if (WorkflowActivity != null && !WorkflowActivity.ChangeTracker.ChangeTrackingEnabled)
                {
                    WorkflowActivity.StartTracking();
                }
            }
        }
    
        private void FixupChildren(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (WorkflowInstance item in e.NewItems)
                {
                    item.Parent = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Children", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (WorkflowInstance item in e.OldItems)
                {
                    if (ReferenceEquals(item.Parent, this))
                    {
                        item.Parent = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Children", item);
                    }
                }
            }
        }

        #endregion

    }
}
