//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Virinco.WATS.Service.MES.Contract
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(WorkflowInstance))]
    [KnownType(typeof(WorkflowActivityLog))]
    public partial class WorkflowActivity: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid WorkflowActivityId
        {
            get { return _workflowActivityId; }
            set
            {
                if (_workflowActivityId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'WorkflowActivityId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _workflowActivityId = value;
                    OnPropertyChanged("WorkflowActivityId");
                }
            }
        }
        private System.Guid _workflowActivityId;
    
        [DataMember]
        public System.Guid WorkflowDefinitionId
        {
            get { return _workflowDefinitionId; }
            set
            {
                if (_workflowDefinitionId != value)
                {
                    _workflowDefinitionId = value;
                    OnPropertyChanged("WorkflowDefinitionId");
                }
            }
        }
        private System.Guid _workflowDefinitionId;
    
        [DataMember]
        public string ActivityPath
        {
            get { return _activityPath; }
            set
            {
                if (_activityPath != value)
                {
                    _activityPath = value;
                    OnPropertyChanged("ActivityPath");
                }
            }
        }
        private string _activityPath;
    
        [DataMember]
        public string ActivityName
        {
            get { return _activityName; }
            set
            {
                if (_activityName != value)
                {
                    _activityName = value;
                    OnPropertyChanged("ActivityName");
                }
            }
        }
        private string _activityName;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<WorkflowInstance> WorkflowInstances
        {
            get
            {
                if (_workflowInstances == null)
                {
                    _workflowInstances = new TrackableCollection<WorkflowInstance>();
                    _workflowInstances.CollectionChanged += FixupWorkflowInstances;
                }
                return _workflowInstances;
            }
            set
            {
                if (!ReferenceEquals(_workflowInstances, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_workflowInstances != null)
                    {
                        _workflowInstances.CollectionChanged -= FixupWorkflowInstances;
                    }
                    _workflowInstances = value;
                    if (_workflowInstances != null)
                    {
                        _workflowInstances.CollectionChanged += FixupWorkflowInstances;
                    }
                    OnNavigationPropertyChanged("WorkflowInstances");
                }
            }
        }
        private TrackableCollection<WorkflowInstance> _workflowInstances;
    
        [DataMember]
        public TrackableCollection<WorkflowActivityLog> WorkflowActivityLogs
        {
            get
            {
                if (_workflowActivityLogs == null)
                {
                    _workflowActivityLogs = new TrackableCollection<WorkflowActivityLog>();
                    _workflowActivityLogs.CollectionChanged += FixupWorkflowActivityLogs;
                }
                return _workflowActivityLogs;
            }
            set
            {
                if (!ReferenceEquals(_workflowActivityLogs, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_workflowActivityLogs != null)
                    {
                        _workflowActivityLogs.CollectionChanged -= FixupWorkflowActivityLogs;
                    }
                    _workflowActivityLogs = value;
                    if (_workflowActivityLogs != null)
                    {
                        _workflowActivityLogs.CollectionChanged += FixupWorkflowActivityLogs;
                    }
                    OnNavigationPropertyChanged("WorkflowActivityLogs");
                }
            }
        }
        private TrackableCollection<WorkflowActivityLog> _workflowActivityLogs;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            WorkflowInstances.Clear();
            WorkflowActivityLogs.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupWorkflowInstances(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (WorkflowInstance item in e.NewItems)
                {
                    item.WorkflowActivity = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("WorkflowInstances", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (WorkflowInstance item in e.OldItems)
                {
                    if (ReferenceEquals(item.WorkflowActivity, this))
                    {
                        item.WorkflowActivity = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("WorkflowInstances", item);
                    }
                }
            }
        }
    
        private void FixupWorkflowActivityLogs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (WorkflowActivityLog item in e.NewItems)
                {
                    item.WorkflowActivity = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("WorkflowActivityLogs", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (WorkflowActivityLog item in e.OldItems)
                {
                    if (ReferenceEquals(item.WorkflowActivity, this))
                    {
                        item.WorkflowActivity = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("WorkflowActivityLogs", item);
                    }
                }
            }
        }

        #endregion

    }
}
