# Type stubs for pyWATS synchronous API
# AUTO-GENERATED - DO NOT EDIT MANUALLY
# Generated by scripts/generate_type_stubs.py

from typing import Optional
from .config import ErrorMode, RetryConfig
from .station import Station, StationRegistry

from .domains.report.service import SyncReportService
from .domains.product.service import SyncProductService
from .domains.asset.service import SyncAssetService
from .domains.production.service import SyncProductionService
from .domains.software.service import SyncSoftwareService
from .domains.analytics.service import SyncAnalyticsService
from .domains.rootcause.service import SyncRootCauseService
from .domains.scim.service import SyncScimService
from .domains.process.service import SyncProcessService

class pyWATS:
    """Type-safe synchronous WATS API client."""

    def __init__(
        self,
        base_url: str,
        *,
        api_key: Optional[str] = None,
        client_id: Optional[str] = None,
        client_secret: Optional[str] = None,
        username: Optional[str] = None,
        password: Optional[str] = None,
        timeout: int = 30,
        error_mode: ErrorMode = ErrorMode.RAISE,
        retry_config: Optional[RetryConfig] = None,
        station: Optional[Station] = None,
    ) -> None: ...

    @property
    def report(self) -> SyncReportService: ...

    @property
    def product(self) -> SyncProductService: ...

    @property
    def asset(self) -> SyncAssetService: ...

    @property
    def production(self) -> SyncProductionService: ...

    @property
    def software(self) -> SyncSoftwareService: ...

    @property
    def analytics(self) -> SyncAnalyticsService: ...

    @property
    def rootcause(self) -> SyncRootCauseService: ...

    @property
    def scim(self) -> SyncScimService: ...

    @property
    def process(self) -> SyncProcessService: ...

    @property
    def base_url(self) -> str: ...

    @property
    def timeout(self) -> int: ...

    @timeout.setter
    def timeout(self, value: int) -> None: ...

    @property
    def error_mode(self) -> ErrorMode: ...

    @property
    def retry_config(self) -> RetryConfig: ...

    @retry_config.setter
    def retry_config(self, value: RetryConfig) -> None: ...

    @property
    def station(self) -> Optional[Station]: ...

    @station.setter
    def station(self, station: Optional[Station]) -> None: ...

    @property
    def stations(self) -> StationRegistry: ...

    def test_connection(self) -> bool: ...

    def get_version(self) -> Optional[str]: ...

    def close(self) -> None: ...

    def __enter__(self) -> 'pyWATS': ...

    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
