//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.virinco.com/WATS/Wats-Client-Service/Converters.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.virinco.com/WATS/Wats-Client-Service/Converters.xsd", IsNullable=false)]
public partial class converters {
    
    private convertersConverter[] converterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("converter")]
    public convertersConverter[] converter {
        get {
            return this.converterField;
        }
        set {
            this.converterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.virinco.com/WATS/Wats-Client-Service/Converters.xsd")]
public partial class convertersConverter {
    
    private ParametersCollection sourceField;
    
    private ParametersCollection destinationField;
    
    private string nameField;
    
    private string assemblyField;
    
    private string classField;
    
    /// <remarks/>
    public ParametersCollection Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public ParametersCollection Destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string assembly {
        get {
            return this.assemblyField;
        }
        set {
            this.assemblyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.virinco.com/WATS/Wats-Client-Service/Converters.xsd")]
public partial class ParametersCollection {
    
    private ParametersCollectionParameter[] parameterField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public ParametersCollectionParameter[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.virinco.com/WATS/Wats-Client-Service/Converters.xsd")]
public partial class ParametersCollectionParameter {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    [XmlIgnore]
    public string Value { get; set; }

    [XmlText]
    public XmlNode[] CDataContent
    {
        get
        {
            return new XmlNode[] { new XmlDocument().CreateCDataSection(Value) };
        }
        set
        {
            if (value == null)            
                Value = null;
            else
            {
                if (value.Length != 1)            
                    throw new InvalidOperationException($"Invalid array length {value.Length}");            

                Value = value[0].Value;
            }
        }
    }
}
